/* Deterministic, local-only production helpers. */
(function boothRuntime(){
 'use strict';const form=document.querySelector('[data-instrument]');if(!form)return;const output=document.querySelector('[data-result-text]'),status=document.querySelector('[data-result-state]'),error=document.querySelector('[data-input-error]'),copy=document.querySelector('[data-copy-result]'),copied=document.querySelector('[data-result-copy-state]');let revision=0,snapshot='',ready=false;
 const field=n=>form.elements.namedItem(n),fail=(n,m)=>{const e=new Error(m);e.field=n;throw e;};
 const badUnicode=s=>/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f-\u009f]|\p{Cs}/u.test(s);
 function normalized(n,max){let s=field(n).value;if(s.length>max*2||badUnicode(s))fail(n,'输入过长或包含不支持的控制字符。');s=s.normalize('NFKC').replace(/\r\n?/g,'\n');if([...s].length>max)fail(n,'规范化后的输入过长。');return s;}
 function lines(n,max,count){const a=normalized(n,max).split('\n').map(s=>s.trim()).filter(Boolean);if(!a.length||a.length>count)fail(n,'请输入 1–'+count+' 个非空行。');return a;}
 function integer(n,min,max){const s=normalized(n,32).trim();if(!/^(0|[1-9]\d*)$/.test(s)||Number(s)<min||Number(s)>max)fail(n,'请输入 '+min+'–'+max+' 的普通整数，不加前导零。');return Number(s);}
 function option(n,allowed){const s=field(n).value;if(!allowed.includes(s))fail(n,'请选择支持的选项。');return s;}
 const time=s=>[Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(n=>String(n).padStart(2,'0')).join(':');
 const millis=m=>time(Math.floor(m/1000))+','+String(m%1000).padStart(3,'0');
 function label(s,n,row,max){const t=s.trim().replace(/\s+/gu,' ');if(!t||[...t].length>max)fail(n,'第 '+row+' 行标签应为 1–'+max+' 码点。');return t;}
 const algorithms=[
 ()=>{let total=0;const rows=lines('scenes',6000,60).map((s,i)=>{const parts=s.split('|');if(parts.length!==2)fail('scenes','第 '+(i+1)+' 行必须且只能有一个 |。');const title=label(parts[0],'scenes',i+1,80),d=parts[1].trim();if(!/^(0|[1-9]\d{0,2}):[0-5]\d$/.test(d))fail('scenes','第 '+(i+1)+' 行时长格式无效。');const [m,sec]=d.split(':').map(Number),duration=m*60+sec;if(!duration)fail('scenes','镜次时长必须大于零。');const start=total;total+=duration;if(total>43200)fail('scenes','总片长不得超过 12 小时。');return {title,start,end:total,duration};});const longest=rows.reduce((a,b)=>b.duration>a.duration?b:a);return '镜次数：'+rows.length+'\n总片长：'+time(total)+'\n最长镜次：'+longest.title+' · '+longest.duration+' 秒\n\n'+rows.map((r,i)=>String(i+1).padStart(2,'0')+' '+r.title+'\nIN '+time(r.start)+' | OUT '+time(r.end)+' | '+r.duration+' 秒').join('\n\n')+'\n\n仅为连续镜次提示，不读取媒体或实际剪辑点。';},
 ()=>{const fps=Number(option('fps',['24','25','30','48','50','60'])),direction=option('direction',['to-frames','to-timecode']),max=360000*fps-1;const result=lines('entries',3000,100).map((s,i)=>{if(direction==='to-frames'){const m=s.match(/^(\d{2}):([0-5]\d):([0-5]\d):(\d{2})$/);if(!m||Number(m[4])>=fps)fail('entries','第 '+(i+1)+' 行时间码无效或帧位超过帧率。');return s+' → '+((Number(m[1])*3600+Number(m[2])*60+Number(m[3]))*fps+Number(m[4]));}if(!/^(0|[1-9]\d*)$/.test(s)||Number(s)>max)fail('entries','第 '+(i+1)+' 行帧序号超出所选帧率范围。');const n=Number(s);return s+' → '+time(Math.floor(n/fps))+':'+String(n%fps).padStart(2,'0');});return '帧率：'+fps+' fps\n记录数：'+result.length+'\n\n'+result.join('\n')+'\n\n整数帧率、零起始、非丢帧标签；不读取媒体时间。';},
 ()=>{const rows=lines('windows',16000,80).map((s,i)=>{const parts=s.split('|');if(parts.length!==2)fail('windows','第 '+(i+1)+' 行必须且只能有一个 |。');const title=label(parts[0],'windows',i+1,60),m=parts[1].trim().match(/^(\d{2}):([0-5]\d):([0-5]\d),(\d{3})\s*-->\s*(\d{2}):([0-5]\d):([0-5]\d),(\d{3})$/);if(!m)fail('windows','第 '+(i+1)+' 行时间窗格式无效。');const start=((+m[1]*60 + +m[2])*60 + +m[3])*1000 + +m[4],end=((+m[5]*60 + +m[6])*60 + +m[7])*1000 + +m[8];if(end<=start)fail('windows','第 '+(i+1)+' 行出点必须晚于入点。');return {title,start,end,index:i+1};});const overlaps=[];for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++){const n=Math.min(rows[i].end,rows[j].end)-Math.max(rows[i].start,rows[j].start);if(n>0)overlaps.push(rows[i].index+' ↔ '+rows[j].index+'：'+n+' ms');}const sorted=[...rows].sort((a,b)=>a.start-b.start||a.index-b.index),gaps=[];let edge=sorted[0].end,gapTotal=0;for(const r of sorted.slice(1)){if(r.start>edge){gaps.push(millis(edge)+' → '+millis(r.start)+'：'+(r.start-edge)+' ms');gapTotal+=r.start-edge;}edge=Math.max(edge,r.end);}const inversions=[];for(let i=1;i<rows.length;i++)if(rows[i].start<rows[i-1].start)inversions.push((i+1)+' 在 '+i+' 之前开始');return '窗口数：'+rows.length+'\n交叠对数：'+overlaps.length+'\n空档数：'+gaps.length+'\n空档总长：'+gapTotal+' ms\n相邻入点倒序：'+inversions.length+'\n\n交叠\n'+(overlaps.join('\n')||'无')+'\n\n空档\n'+(gaps.join('\n')||'无')+'\n\n输入次序\n'+(inversions.join('\n')||'无倒序')+'\n\n行号索引\n'+rows.map(r=>r.index+' '+r.title).join('\n')+'\n\n半开时间窗；不检查字幕文本、音频或片段前后空白。';},
 ()=>{const n=integer('frames',1,1000000000),k=integer('samples',1,200),one=option('numbering',['zero','one'])==='one';if(k>n)fail('samples','印样数量不能大于总帧数。');const result=Array.from({length:k},(_,i)=>Number((BigInt(2*i+1)*BigInt(n))/(2n*BigInt(k)))+(one?1:0));return '总帧数：'+n+'\n印样数：'+k+'\n显示编号：'+(one?'从 1 开始':'从 0 开始')+'\n\n'+result.map((v,i)=>String(i+1).padStart(2,'0')+' | '+v).join('\n')+'\n\n每个等宽分段取中点下取整；不分析镜头内容或关键帧。';},
 ()=>{const capacity=integer('capacity',1,1000000),rows=lines('pieces',6000,60).map((s,i)=>{const parts=s.split('|');if(parts.length!==2)fail('pieces','第 '+(i+1)+' 行必须且只能有一个 |。');const title=label(parts[0],'pieces',i+1,60),x=parts[1].trim();if(!/^[1-9]\d*$/.test(x)||Number(x)>capacity)fail('pieces','第 '+(i+1)+' 行容量必须为不超过每卷容量的正整数。');return {title,size:Number(x),index:i+1};});const sorted=[...rows].sort((a,b)=>b.size-a.size||a.index-b.index),bins=[];for(const r of sorted){let bin=bins.find(b=>b.used+r.size<=capacity);if(!bin){bin={used:0,items:[]};bins.push(bin);}bin.used+=r.size;bin.items.push(r);}const total=rows.reduce((s,r)=>s+r.size,0);return '片段数：'+rows.length+'\n每卷容量：'+capacity+'\n使用卷数：'+bins.length+'\n总用量：'+total+'\n总余量：'+(bins.length*capacity-total)+'\n理论下界：'+Math.ceil(total/capacity)+' 卷\n\n'+bins.map((b,i)=>'卷 '+(i+1)+' | 用量 '+b.used+' | 余量 '+(capacity-b.used)+'\n'+b.items.map(r=>'  #'+r.index+' '+r.title+' | '+r.size).join('\n')).join('\n\n')+'\n\n稳定首次适配降序；不保证最少卷数，下界不一定可达。';}
 ];
 function clear(message){revision++;ready=false;snapshot='';output.textContent='';copy.disabled=true;copied.textContent='';status.textContent=message;error.textContent='';for(const e of form.querySelectorAll('[aria-invalid]'))e.removeAttribute('aria-invalid');}
 form.querySelector('[type=submit]').disabled=false;form.addEventListener('input',()=>clear('输入已改变，请重新生成。'));form.addEventListener('change',()=>clear('输入已改变，请重新生成。'));form.addEventListener('reset',()=>clear('已恢复示例，请重新生成。'));
 form.addEventListener('submit',e=>{e.preventDefault();clear('正在整理。');try{snapshot=algorithms[Number(form.dataset.instrument)]();output.textContent=snapshot;ready=true;copy.disabled=false;status.textContent='本次记录已生成，仅在本页保留。';}catch(e){error.textContent=e.message;status.textContent='未生成记录，请检查输入。';const target=field(e.field);if(target){target.setAttribute('aria-invalid','true');target.setAttribute('aria-errormessage','nc63-input-error');target.focus();}}});
 copy.addEventListener('click',async()=>{if(!ready||!snapshot)return;const epoch=revision,text=snapshot;copy.disabled=true;try{await navigator.clipboard.writeText(text);if(epoch===revision)copied.textContent='制作记录已复制。';}catch{if(epoch===revision)copied.textContent='无法复制，可手动选择上方记录。';}finally{if(epoch===revision)copy.disabled=!ready;}});
})();
