/* Local presentation controls; no input leaves the page. */
(function projectorRuntime(){
 'use strict';const root=document.documentElement,key='noir-cinema-063-lamp';root.classList.remove('nc63-nojs');const lamp=document.querySelector('[data-lamp-toggle]');let saved;try{saved=localStorage.getItem(key);}catch{}
 function theme(t){root.dataset.theme=t;document.querySelector('meta[name="theme-color"]').content=t==='house'?'#e7e3da':'#080808';lamp.textContent=t==='house'?'熄灯':'亮灯';lamp.setAttribute('aria-pressed',String(t==='house'));lamp.setAttribute('aria-label',t==='house'?'切换到黑场主题':'切换到亮灯主题');}
 theme(saved==='house'?'house':'noir');lamp.addEventListener('click',()=>{const t=root.dataset.theme==='house'?'noir':'house';theme(t);try{localStorage.setItem(key,t);}catch{}});
 const menu=document.getElementById('nc63-menu'),toggle=document.getElementById('nc63-menu-button');function close(focus=false){menu.classList.remove('nc63-open');toggle.setAttribute('aria-expanded','false');toggle.querySelector('i').textContent='打开场次';if(focus)toggle.focus();}
 toggle.addEventListener('click',()=>{if(toggle.getAttribute('aria-expanded')==='true')return close();menu.classList.add('nc63-open');toggle.setAttribute('aria-expanded','true');toggle.querySelector('i').textContent='关闭场次';menu.querySelector('a').focus();});menu.addEventListener('click',e=>{if(e.target.closest('a'))close();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&toggle.getAttribute('aria-expanded')==='true')close(true);});addEventListener('resize',()=>{if(innerWidth>900)close();});
 const copy=document.querySelector('[data-copy-code]');if(copy){copy.disabled=false;copy.addEventListener('click',async()=>{copy.disabled=true;const state=document.querySelector('[data-code-state]');try{await navigator.clipboard.writeText(document.getElementById('nc63-code').textContent.trim());state.textContent='已复制，可粘贴使用。';}catch{state.textContent='无法复制，请手动选择上方文字。';}finally{copy.disabled=false;}});}
 const filter=document.querySelector('[data-screen-filter]');if(filter){filter.hidden=false;const rows=[...document.querySelectorAll('[data-screen-group]')],status=filter.querySelector('[data-filter-state]');function update(){const group=filter.elements.room.value,q=filter.elements.keyword.value.normalize('NFKC').trim().toLocaleLowerCase();let count=0;for(const row of rows){row.hidden=!(group==='all'||row.dataset.screenGroup===group)||!row.querySelector('h3').textContent.normalize('NFKC').toLocaleLowerCase().includes(q);if(!row.hidden)count++;}status.textContent=count?'当前有 '+count+' 场可读。':'没有匹配场刊，可清除筛选。';}filter.addEventListener('input',update);filter.addEventListener('change',update);filter.addEventListener('submit',e=>e.preventDefault());filter.addEventListener('reset',()=>setTimeout(update,0));update();}
 const search=document.querySelector('[data-local-search]');if(search){search.querySelector('button').disabled=false;const rows=[...document.querySelectorAll('[data-search-item]')],status=search.querySelector('[data-search-state]');search.addEventListener('submit',e=>{e.preventDefault();const q=search.elements.query.value.normalize('NFKC').trim().toLocaleLowerCase();let n=0;for(const row of rows){row.hidden=!row.textContent.normalize('NFKC').toLocaleLowerCase().includes(q);if(!row.hidden)n++;}status.textContent=n?'找到 '+n+' 个本站入口。':'没有匹配入口，可返回放映馆。';});search.addEventListener('input',()=>{rows.forEach(r=>r.hidden=false);status.textContent='关键词已改变，请重新查找。';});}
 const progress=document.querySelector('[data-reading-progress]');if(progress){const update=()=>{const max=root.scrollHeight-innerHeight;progress.style.width=Math.max(0,Math.min(100,max?scrollY/max*100:100))+'%';};addEventListener('scroll',update,{passive:true});addEventListener('resize',update);addEventListener('load',update);update();}
})();
