/* Oat Profile: local reading and navigation, no input persistence. */
(()=>{'use strict';
const root=document.documentElement,key='oat-profile-057-theme',theme=document.querySelector('[data-theme-toggle]');root.classList.remove('op57-nojs');
function setTheme(t){root.dataset.theme=t;document.querySelector('meta[name="theme-color"]').content=t==='dark'?'#181512':'#eee7da';if(theme){theme.textContent=t==='dark'?'日间':'夜间';theme.setAttribute('aria-pressed',String(t==='dark'));theme.setAttribute('aria-label',t==='dark'?'切换到日间模式':'切换到夜间模式');}}
let saved='light';try{if(localStorage.getItem(key)==='dark')saved='dark';}catch{}setTheme(saved);theme?.addEventListener('click',()=>{const t=root.dataset.theme==='dark'?'light':'dark';setTheme(t);try{localStorage.setItem(key,t);}catch{}});
const menu=document.getElementById('op57-menu'),toggle=document.querySelector('.op57-menu-button');function close(focus=false){menu?.classList.remove('op57-open');if(toggle){toggle.setAttribute('aria-expanded','false');toggle.querySelector('[aria-hidden]').textContent='≡';toggle.querySelector('.op57-sr').textContent='打开导航';if(focus)toggle.focus();}}
toggle?.addEventListener('click',()=>{if(toggle.getAttribute('aria-expanded')==='true'){close();return;}toggle.setAttribute('aria-expanded','true');toggle.querySelector('[aria-hidden]').textContent='×';toggle.querySelector('.op57-sr').textContent='关闭导航';menu.classList.add('op57-open');menu.querySelector('a').focus();});menu?.addEventListener('click',e=>{if(e.target.closest('a'))close();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&toggle?.getAttribute('aria-expanded')==='true')close(true);});window.addEventListener('resize',()=>{if(innerWidth>680)close();});
const copy=document.querySelector('[data-copy-code]'),code=document.getElementById('op57-code'),status=document.querySelector('[data-code-state]');if(copy){copy.disabled=false;copy.addEventListener('click',async()=>{copy.disabled=true;status.textContent='复制中…';try{await navigator.clipboard.writeText(code.textContent.trim());status.textContent='已复制邀请码。';}catch{status.textContent='复制不可用，请手动选择邀请码。';}finally{copy.disabled=false;}});}
const form=document.querySelector('[data-local-search]');if(form){form.querySelector('button').disabled=false;const field=form.elements.query,list=[...document.querySelectorAll('[data-search-item]')],message=form.querySelector('[data-search-state]');form.addEventListener('submit',e=>{e.preventDefault();const q=field.value.normalize('NFKC').trim().toLowerCase();let count=0;for(const item of list){item.hidden=!item.textContent.normalize('NFKC').toLowerCase().includes(q);if(!item.hidden)count++;}message.textContent=count?'找到 '+count+' 个入口。':'没有匹配标题，清空关键词可查看全部入口。';});field.addEventListener('input',()=>{message.textContent='关键词已改变，请重新查找。';});}
const progress=document.querySelector('[data-reading-progress]');if(progress){const update=()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max<=0?100:Math.max(0,Math.min(100,scrollY/max*100)))+'%';};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);window.addEventListener('load',update);document.querySelectorAll('details').forEach(d=>d.addEventListener('toggle',update));}
})();
