/* Five independent, local-only desk instruments. */
(()=>{'use strict';const form=document.querySelector('[data-instrument]');if(!form)return;const error=document.querySelector('[data-input-error]'),state=document.querySelector('[data-result-state]'),output=document.querySelector('[data-result-text]'),copy=document.querySelector('[data-copy-result]'),copyState=document.querySelector('[data-result-copy-state]');let revision=0;form.querySelector('button[type=submit]').disabled=false;
const fail=(name,message)=>{const e=new Error(message);e.field=name;throw e;},norm=s=>s.normalize('NFKC').trim(),value=name=>norm(form.elements[name].value);
function integer(name,min,max){const s=value(name);if(!/^(0|[1-9]\d*)$/.test(s)||s.length>8||Number(s)<min||Number(s)>max)fail(name,'请输入 '+min+'–'+max+' 的整数，不含前导零、符号、小数或指数。');return Number(s);}
function lines(name,min,max){const s=value(name);if(s.length>6000)fail(name,'列表最多 6000 个归一化后的 UTF-16 代码单元。');const rows=s.split(/\r?\n/).map(x=>x.trim());if(rows.length<min||rows.length>max||rows.some(x=>!x))fail(name,'请输入 '+min+'–'+max+' 行，不留中间空行。');return rows;}
function label(s,name,seen){s=norm(s);if(!s||[...s].length>20||/[,\n\r:]/.test(s))fail(name,'名称为 1–20 个码点，不能含逗号、冒号或换行。');const id=s.toLowerCase();if(seen.has(id))fail(name,'归一化后忽略大小写，名称不能重复。');seen.add(id);return s;}
function date(s,name){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))fail(name,'日期必须为完整 YYYY-MM-DD。');const[y,m,d]=s.split('-').map(Number),stamp=Date.UTC(y,m-1,d),t=new Date(stamp);if(y<1900||y>2199||t.getUTCFullYear()!==y||t.getUTCMonth()!==m-1||t.getUTCDate()!==d)fail(name,'请输入 1900–2199 年间真实存在的日期。');return stamp/86400000;}
const day=n=>new Date(n*86400000).toISOString().slice(0,10);
const runners={
 'field-inventory':()=>{const fields=[['source','一手来源地址',30],['scope','适用范围',20],['version','版本或条款',20],['effective','生效日期',15],['owner','复核责任人',15]],selected=fields.filter(([n])=>form.elements[n].checked),absent=fields.filter(([n])=>!form.elements[n].checked),score=selected.reduce((s,f)=>s+f[2],0);return '固定权重总分：'+score+' / 100\n已记录字段：'+selected.length+' / 5\n未记录字段：'+absent.length+'\n\n已记录：'+(selected.map(f=>f[1]).join('、')||'无')+'\n未记录：'+(absent.map(f=>f[1]).join('、')||'无')+'\n\n只盘点字段，不判断正确性，不作为发布许可。';},
 'date-union':()=>{const seen=new Set(),ranges=lines('periods',1,30).map(row=>{const p=row.split(',').map(x=>x.trim());if(p.length!==3)fail('periods','每行格式：名称,开始日期,结束日期。');label(p[0],'periods',seen);const start=date(p[1],'periods'),end=date(p[2],'periods');if(start>end)fail('periods','开始日期不能晚于结束日期。');return{start,end};});const original=ranges.reduce((s,r)=>s+r.end-r.start+1,0);ranges.sort((a,b)=>a.start-b.start||a.end-b.end);const union=[];for(const r of ranges){const last=union.at(-1);if(last&&r.start<=last.end+1)last.end=Math.max(last.end,r.end);else union.push({...r});}const days=union.reduce((s,r)=>s+r.end-r.start+1,0);return '输入区间：'+ranges.length+'\n原始合计：'+original+' 天\n不重复天数：'+days+' 天\n重复覆盖天数：'+(original-days)+' 天\n合并区间：'+union.length+'\n\n'+union.map(r=>day(r.start)+' → '+day(r.end)+' / '+(r.end-r.start+1)+' 天').join('\n')+'\n\n含首尾日；合并重叠或相邻段。重复覆盖指原始合计减并集，不是重叠日期的不同天数。';},
 'card-imposition':()=>{function mm(name,min){const s=value(name);if(!/^(0|[1-9]\d*)(\.\d)?$/.test(s)||s.length>7)fail(name,'毫米数只能使用普通十进制，最多一位小数。');const parts=s.split('.'),n=BigInt(parts[0])*10n+BigInt(parts[1]||'0');if(n<BigInt(min)*10n||n>50000n)fail(name,'尺寸须为 '+min+'–5000 mm。');return n;}const w=mm('paperW',1),h=mm('paperH',1),cw=mm('cardW',1),ch=mm('cardH',1),margin=mm('margin',0),gap=mm('gap',0),q=BigInt(integer('quantity',1,10000)),mode=value('orientation');if(!['auto','original'].includes(mode))fail('orientation','请选择可用的旋转方案。');const usableW=w-margin*2n,usableH=h-margin*2n;function layout(a,b){const cols=usableW<a?0n:(usableW+gap)/(a+gap),rows=usableH<b?0n:(usableH+gap)/(b+gap);return{cols,rows,count:cols*rows};}const a=layout(cw,ch),b=layout(ch,cw),rotated=mode==='auto'&&b.count>a.count,chosen=rotated?b:a;if(!chosen.count)return '没有可用方案。\n可用纸面不足或卡片放不下。\n请核对四边留边、卡片尺寸与方向。';const pages=(q+chosen.count-1n)/chosen.count;return '选择方向：'+(rotated?'旋转 90°':'原方向')+'\n列数：'+chosen.cols+'\n行数：'+chosen.rows+'\n每页容量：'+chosen.count+'\n需要卡片：'+q+'\n需要纸张：'+pages+'\n末页使用：'+(q-(pages-1n)*chosen.count)+'\n末页空位：'+(pages*chosen.count-q)+'\n\n原方向容量：'+a.count+(mode==='auto'?'\n旋转方向容量：'+b.count:'')+'\n\n单一方向矩形网格，不含出血、刀线、咬口或混合方向拼版。';},
 'round-robin':()=>{const seen=new Set(),names=lines('people',2,16).map(s=>label(s,'people',seen)),circle=names.map((_,i)=>i);if(circle.length%2)circle.push(null);const rounds=[],n=circle.length;for(let r=0;r<n-1;r++){const pairs=[],rest=[];for(let i=0;i<n/2;i++){const a=circle[i],b=circle[n-1-i];if(a===null||b===null)rest.push(names[a===null?b:a]);else pairs.push(names[a]+' ↔ '+names[b]);}rounds.push('第 '+(r+1)+' 轮\n'+pairs.join('\n')+(rest.length?'\n轮空：'+rest[0]:''));circle.splice(1,0,circle.pop());}return '参与人数：'+names.length+'\n轮次：'+rounds.length+'\n配对总数：'+(names.length*(names.length-1)/2)+'\n每人配对：'+(names.length-1)+'\n\n'+rounds.join('\n\n')+'\n\n只生成单循环配对表，不处理真实日期、偏好或可用时段。';},
 'text-columns':()=>{const width=integer('columns',1,80),height=integer('rows',1,30),raw=form.elements.text.value;if(raw.length>32000)fail('text','原始正文最多 32000 个 UTF-16 代码单元。');const text=raw.replace(/\r\n?/g,'\n');if(!text.trim()||/[\u0000-\u0009\u000b-\u001f\u007f-\u009f]/.test(text))fail('text','请输入非空正文，不含制表符或控制字符。');if(typeof Intl.Segmenter!=='function')fail('text','当前浏览器不支持字素分段，请换用支持 Intl.Segmenter 的浏览器。');const segmenter=new Intl.Segmenter(undefined,{granularity:'grapheme'});let total=0;const lines=[];for(const source of text.split('\n')){const units=[...segmenter.segment(source)].map(x=>x.segment);total+=units.length;if(total>4000)fail('text','正文最多 4000 个字素，不计换行。');if(!units.length)lines.push('');else for(let i=0;i<units.length;i+=width)lines.push(units.slice(i,i+width).join(''));}const cards=[];for(let i=0;i<lines.length;i+=height)cards.push(lines.slice(i,i+height));return '正文字符（字素）：'+total+'\n拆分行数：'+lines.length+'\n需要卡片：'+cards.length+'\n每行配额：'+width+'\n每卡行数：'+height+'\n\n'+cards.map((c,i)=>'卡片 '+(i+1)+' / '+c.length+' 行\n'+c.join('\n')).join('\n\n')+'\n\n字素配额不等于实际视觉宽度；保留显式空行与尾部换行。';}
};
function clear(){revision++;output.textContent='';copy.disabled=true;copyState.textContent='';error.textContent='';for(const e of form.querySelectorAll('[aria-invalid]')){e.removeAttribute('aria-invalid');e.removeAttribute('aria-errormessage');}state.textContent='输入已改变，请重新生成。';}
form.addEventListener('input',clear);form.addEventListener('change',e=>{if(e.target.type==='checkbox'||e.target.tagName==='SELECT')clear();});form.addEventListener('reset',()=>{clear();state.textContent='已恢复示例，等待生成。';});form.addEventListener('submit',e=>{e.preventDefault();clear();try{output.textContent=runners[form.dataset.instrument]();copy.disabled=false;state.textContent='记录已生成。';}catch(err){error.textContent=err.message;state.textContent='请修正输入后重试。';const field=form.elements[err.field];if(field){field.setAttribute('aria-invalid','true');field.setAttribute('aria-errormessage','op57-field-error');field.focus();}}});
copy.addEventListener('click',async()=>{if(copy.disabled)return;const version=revision,text=output.textContent;copy.disabled=true;copyState.textContent='复制中…';try{await navigator.clipboard.writeText(text);if(version===revision)copyState.textContent='已复制回执。';}catch{if(version===revision)copyState.textContent='复制不可用，请手动选择结果。';}finally{if(version===revision)copy.disabled=false;}});
})();
