(function collectionRuntime(){
 'use strict';
 const root=document.documentElement;root.classList.add('hb65-script');
 const paperButton=document.querySelector('[data-paper-toggle]'),key='moss-bloom-065-paper';
 const paper=value=>{const next=value==='night'?'night':'day';root.dataset.paper=next;paperButton.textContent=next==='night'?'日藏':'夜藏';paperButton.setAttribute('aria-label',next==='night'?'切换到日藏主题':'切换到夜藏主题');};
 paperButton.hidden=false;try{paper(localStorage.getItem(key));}catch{paper('day');}paperButton.addEventListener('click',()=>{paper(root.dataset.paper==='night'?'day':'night');try{localStorage.setItem(key,root.dataset.paper);}catch{}});
 const drawer=document.querySelector('.hb65-drawer'),button=document.querySelector('.hb65-drawer-button');button.hidden=false;
 const close=(restore=false)=>{drawer.classList.remove('hb65-open');button.setAttribute('aria-expanded','false');if(restore)button.focus();};
 button.addEventListener('click',()=>{const open=!drawer.classList.contains('hb65-open');drawer.classList.toggle('hb65-open',open);button.setAttribute('aria-expanded',String(open));if(open)drawer.querySelector('a').focus();});
 drawer.addEventListener('click',e=>{if(e.target.closest('a'))close();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&drawer.classList.contains('hb65-open'))close(true);});window.addEventListener('resize',()=>{if(innerWidth>920)close();});
 const copy=document.querySelector('[data-copy-code]');if(copy){copy.disabled=false;copy.addEventListener('click',async()=>{copy.disabled=true;const state=document.querySelector('[data-code-state]');try{await navigator.clipboard.writeText(document.getElementById('hb65-code').textContent.trim());state.textContent='代码已复制。';}catch{state.textContent='浏览器未允许复制，请手动选择上方代码。';}finally{copy.disabled=false;}});}
 const progress=document.querySelector('[data-reading-progress]');if(progress){const update=()=>{const remaining=root.scrollHeight-innerHeight,value=(remaining>0?Math.min(100,Math.max(0,scrollY/remaining*100)):100)+'%';progress.style.width=innerWidth<=920?value:'100%';progress.style.height=innerWidth<=920?'100%':value;};update();document.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);}
 const normalize=s=>s.normalize('NFKC').trim().toLowerCase(),filter=document.querySelector('[data-collection-filter]');
 if(filter){filter.hidden=false;const items=[...document.querySelectorAll('[data-collection-room]')],run=()=>{let n=0;const q=normalize(filter.elements.keyword.value),room=filter.elements.room.value;for(const item of items){item.hidden=!(normalize(item.querySelector('a b').textContent).includes(q)&&(room==='all'||room===item.dataset.collectionRoom));if(!item.hidden)n++;}filter.querySelector('[data-filter-state]').textContent='当前显示 '+n+' 份馆藏。';};filter.addEventListener('input',run);filter.addEventListener('change',run);filter.addEventListener('submit',e=>e.preventDefault());filter.addEventListener('reset',()=>setTimeout(run,0));run();}
 const search=document.querySelector('[data-local-search]');if(search){const items=[...document.querySelectorAll('[data-search-item]')],state=search.querySelector('[data-search-state]');search.querySelector('button').disabled=false;search.addEventListener('submit',e=>{e.preventDefault();const q=normalize(search.elements.query.value);let n=0;for(const item of items){item.hidden=!normalize(item.textContent).includes(q);if(!item.hidden)n++;}state.textContent='找到 '+n+' 个本站入口。';});search.addEventListener('input',()=>{for(const item of items)item.hidden=false;state.textContent='输入已变化，请重新检索。';});}
})();
