(() => {
 'use strict';
 const one=s=>document.querySelector(s),all=s=>Array.from(document.querySelectorAll(s)),root=document.documentElement,mast=one('.bg70-mast'),menu=one('#bg70-menu'),menuButton=one('#bg70-menu-button'),toggle=one('[data-edition-toggle]'),themeKey='broadsheet-gazette-070-edition';
 function edition(value){const theme=value==='sepia'?'sepia':'ink';root.dataset.edition=theme;one('meta[name="theme-color"]').content=theme==='ink'?'#f1ede2':'#1a1814';if(toggle){toggle.textContent=theme==='ink'?'棕版':'纸版';toggle.setAttribute('aria-label',theme==='ink'?'切换到深棕版':'切换到黑白纸版');}}
 try{edition(localStorage.getItem(themeKey));}catch{edition('ink');}
 if(toggle){toggle.hidden=false;toggle.addEventListener('click',()=>{edition(root.dataset.edition==='ink'?'sepia':'ink');try{localStorage.setItem(themeKey,root.dataset.edition);}catch{}});}
 function closeMenu(focus=false){if(!menuButton)return;menu.classList.remove('bg70-open');menuButton.setAttribute('aria-expanded','false');if(focus)menuButton.focus();}
 if(menuButton){mast.classList.add('bg70-js');menuButton.hidden=false;menuButton.addEventListener('click',()=>{if(menuButton.getAttribute('aria-expanded')==='true')closeMenu();else{menu.classList.add('bg70-open');menuButton.setAttribute('aria-expanded','true');menu.querySelector('a').focus();}});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>closeMenu()));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menuButton.getAttribute('aria-expanded')==='true')closeMenu(true);});document.addEventListener('click',e=>{if(!mast.contains(e.target))closeMenu();});matchMedia('(min-width:961px)').addEventListener('change',e=>{if(e.matches)closeMenu();});}
 const code=one('[data-copy-code]');if(code){code.disabled=false;code.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(one('#bg70-code').textContent.trim());one('[data-code-state]').textContent='代码已复制。';}catch{one('[data-code-state]').textContent='复制未获允许，请手动选择代码。';}});}
 const key=s=>s.normalize('NFKC').trim().toLowerCase();
 const filter=one('[data-report-filter]');if(filter){filter.hidden=false;const update=()=>{const q=key(filter.elements.keyword.value),g=filter.elements.edition.value;let count=0;all('[data-report-edition]').forEach(e=>{e.hidden=!((g==='all'||e.dataset.reportEdition===g)&&key(e.querySelector('a').textContent).includes(q));if(!e.hidden)count++;});one('[data-filter-state]').textContent='显示 '+count+' 篇。';};filter.addEventListener('input',update);filter.addEventListener('change',update);filter.addEventListener('reset',()=>setTimeout(update,0));update();}
 const search=one('[data-local-search]');if(search){search.querySelector('button').disabled=false;search.addEventListener('submit',e=>{e.preventDefault();const q=key(search.elements.query.value);let count=0;all('[data-search-item]').forEach(a=>{a.hidden=!key(a.textContent).includes(q);if(!a.hidden)count++;});one('[data-search-state]').textContent=count?'找到 '+count+' 个页面。':'题名中没有匹配项，请换一个词。';});}
 const progress=one('[data-reading-progress]');if(progress){let pending=false;const update=()=>{const max=root.scrollHeight-innerHeight;progress.style.width=(max>0?Math.min(100,Math.max(0,scrollY/max*100)):100)+'%';pending=false;};addEventListener('scroll',()=>{if(!pending){pending=true;requestAnimationFrame(update);}},{passive:true});addEventListener('resize',update);addEventListener('load',update);update();}
 const form=one('[data-press-tool]');if(!form)return;
 const result=one('[data-result-text]'),status=one('[data-result-status]'),copy=one('[data-copy-result]'),copyStatus=one('[data-result-copy-state]'),error=one('#bg70-error');let revision=0;
 function fail(field,message){const e=new Error(message);e.field=field;throw e;}
 const raw=name=>form.elements.namedItem(name).value;
 function text(name,max,empty=false){const s=raw(name);if(!s.isWellFormed())fail(name,'输入含不完整 Unicode，请重新输入。');if(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f-\u009f]/u.test(s))fail(name,'输入含不可用控制字符。');if(Array.from(s).length>max)fail(name,'输入超过 '+max+' Unicode 码点。');if(!empty&&!s.length)fail(name,'请填写此字段。');return s;}
 function integer(name,min,max){const s=text(name,20).trim();if(!/^\d+$/.test(s))fail(name,'只接受十进制整数。');const n=Number(s);if(!Number.isSafeInteger(n)||n<min||n>max)fail(name,'数值必须在 '+min+'–'+max+' 之间。');return n;}
 function option(name,values){const value=raw(name);if(!values.includes(value))fail(name,'请选择有效选项。');return value;}
 function rows(name){const s=text(name,10000),items=s.replace(/\r\n?/g,'\n').split('\n').map((s,i)=>({text:s.normalize('NFKC').trim(),line:i+1})).filter(r=>r.text);if(!items.length)fail(name,'至少填写一条非空记录。');if(items.length>100)fail(name,'最多接受 100 条非空记录。');return items;}
 const algorithms={
  'quote-attribution':()=>{const items=rows('quotes'),speakers=new Map(),quotes=new Map(),records=items.map((r,i)=>{const parts=r.text.split('|');if(parts.length!==2)fail('quotes','第 '+r.line+' 行必须且只能含一个竖线。');const speaker=parts[0].trim(),quote=parts[1].trim(),slen=Array.from(speaker).length,qlen=Array.from(quote).length;if(slen<1||slen>40)fail('quotes','第 '+r.line+' 行说话者须为 1–40 码点。');if(qlen<1||qlen>500)fail('quotes','第 '+r.line+' 行引语须为 1–500 码点。');const sk=speaker.toLowerCase(),qk=quote.toLowerCase();if(!speakers.has(sk))speakers.set(sk,speaker);const first=quotes.get(qk);if(!first)quotes.set(qk,{index:i+1,speaker:sk});return {speaker,quote,length:qlen,line:r.line,duplicate:first?first.index:0,cross:!!first&&first.speaker!==sk};});return ['引语归属报告','记录：'+records.length,'说话者：'+speakers.size,'重复引语：'+records.filter(r=>r.duplicate).length,'跨人重复：'+records.filter(r=>r.cross).length,'最长引语：'+Math.max(...records.map(r=>r.length))+' 码点','',...records.flatMap((r,i)=>[(i+1)+'. 第 '+r.line+' 行 · '+r.speaker+' · '+r.length+' 码点'+(r.duplicate?' · 重复第 '+r.duplicate+' 条':'')+(r.cross?' · 说话者不同':''),r.quote,'']),'重复仅表示按既定规则相同，不判断归属真伪或抄袭。'].join('\n');},
  'column-flow':()=>{const paragraphs=rows('paragraphs').map(r=>({...r,text:r.text.replace(/\s+/g,' ')})),width=integer('width',10,80),height=integer('height',5,100),gap=Number(option('gap',['0','1'])),flow=[];paragraphs.forEach((r,i)=>{const points=Array.from(r.text);if(points.length>800)fail('paragraphs','第 '+r.line+' 行超过 800 码点。');if(i&&gap)flow.push({text:'',source:0});for(let n=0;n<points.length;n+=width)flow.push({text:points.slice(n,n+width).join(''),source:r.line});});const columns=Math.ceil(flow.length/height);const report=['等格分栏报告','段数：'+paragraphs.length,'格宽：'+width,'栏高：'+height,'段间空行：'+gap,'排版行：'+flow.length,'栏数：'+columns,''];for(let c=0;c<columns;c++){report.push('栏 '+(c+1));flow.slice(c*height,(c+1)*height).forEach((r,j)=>report.push((j+1)+' | '+(r.source?'原第 '+r.source+' 行：'+r.text:'段间空行')));report.push('');}return report.concat('一个码点抽象为一格；不是实际字体宽度或印刷排版。').join('\n');},
  'signature-imposition':()=>{const pages=integer('pages',1,256),capacity=Number(option('signature',['4','8','16','32'])),padded=Math.ceil(pages/4)*4,report=['书帖配页报告','内容页：'+pages,'补空白页：'+(padded-pages),'逻辑总页：'+padded,'每帖容量：'+capacity,'纸张总数：'+padded/4,''];let section=0;const label=n=>n>pages?'空白('+n+')':String(n);for(let start=1;start<=padded;start+=capacity){section++;const count=Math.min(capacity,padded-start+1),end=start+count-1;report.push('帖 '+section+' · 逻辑页 '+start+'–'+end);for(let sheet=0;sheet<count/4;sheet++){report.push('纸 '+(sheet+1)+' 正面：'+label(end-2*sheet)+' | '+label(start+2*sheet));report.push('纸 '+(sheet+1)+' 反面：'+label(start+2*sheet+1)+' | '+label(end-2*sheet-1));}report.push('');}return report.concat('仅为左侧装订逻辑页对；打印方向与双面翻转须另用测试纸验证。').join('\n');},
  'quotation-balance':()=>{const source=text('text',10000,true),points=Array.from(source),pairs=new Map([['“','”'],['‘','’'],['「','」'],['『','』'],['《','》']]),closers=new Set(pairs.values()),stack=[],issues=[];let line=1,column=1,opens=0,closes=0,matched=0,mismatched=0,orphans=0;points.forEach((c,i)=>{const current={c,pos:i+1,line,column};if(pairs.has(c)){opens++;stack.push(current);}else if(closers.has(c)){closes++;const last=stack.pop();if(!last){orphans++;issues.push({...current,message:'孤立右符号 '+c});}else if(pairs.get(last.c)!==c){mismatched++;issues.push({...current,message:'交叉类型 '+last.c+'…'+c+'；左符号位置 '+last.pos+'，预期 '+pairs.get(last.c)});}else matched++;}if(opens+closes>1000)fail('text','受检引号最多 1,000 个。');if(c==='\n'){line++;column=1;}else column++;});stack.forEach(r=>issues.push({...r,message:'未闭合左符号 '+r.c+'；预期 '+pairs.get(r.c)}));issues.sort((a,b)=>a.pos-b.pos);return ['成对引号报告','文本码点：'+points.length,'受检符号：'+(opens+closes),'正确配对：'+matched,'类型交叉：'+mismatched,'孤立右符号：'+orphans,'未闭合左符号：'+stack.length,'问题总数：'+issues.length,'',...(issues.length?issues.map((r,i)=>(i+1)+'. 位置 '+r.pos+'；行 '+r.line+'，列 '+r.column+' · '+r.message):['受检符号未发现配对问题。']),'','仅核对五组成对符号；不处理 ASCII 引号，也不判断内容事实。'].join('\n');},
  'page-coverage':()=>{const items=rows('ranges'),total=integer('total',1,500),coverage=Array.from({length:total},()=>[]),ranges=items.map(r=>{const m=r.text.match(/^(\d+)(?:\s*-\s*(\d+))?$/);if(!m)fail('ranges','第 '+r.line+' 行须为页码或起止范围。');const start=Number(m[1]),end=Number(m[2]||m[1]);if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<1||end<start||end>total)fail('ranges','第 '+r.line+' 行须为 1–'+total+' 内的正向范围。');for(let p=start;p<=end;p++)coverage[p-1].push(r.line);return {start,end,line:r.line};});const missing=[],overlap=[];coverage.forEach((rows,i)=>{if(!rows.length)missing.push(i+1);if(rows.length>1)overlap.push(i+1);});const runs=values=>{const result=[];for(let i=0;i<values.length;){const start=values[i];let end=start;while(i+1<values.length&&values[i+1]===end+1)end=values[++i];result.push(start===end?String(start):start+'–'+end);i++;}return result.length?result.join('，'):'无';};return ['页码覆盖报告','总页数：'+total,'输入范围：'+ranges.length,'已覆盖页：'+(total-missing.length),'缺页：'+missing.length,'重叠页：'+overlap.length,'多余覆盖次数：'+coverage.reduce((n,r)=>n+Math.max(0,r.length-1),0),'缺页范围：'+runs(missing),'重叠范围：'+runs(overlap),'','输入范围',...ranges.map(r=>'第 '+r.line+' 行：'+r.start+'–'+r.end),'','逐页覆盖',...coverage.map((r,i)=>(i+1)+': '+r.length+' 次'+(r.length?' · 输入行 '+r.join(', '):' · 缺页')),'','只描述覆盖情况，不能替代纸张与正文的人工校对。'].join('\n');}
 };
 function clear(){revision++;result.textContent='';copy.disabled=true;copyStatus.textContent='';error.textContent='';form.querySelectorAll('[aria-invalid]').forEach(e=>{e.removeAttribute('aria-invalid');e.removeAttribute('aria-errormessage');});status.textContent='输入已变更，请重新生成';}
 form.querySelector('[type=submit]').disabled=false;form.addEventListener('input',clear);form.addEventListener('change',e=>{if(e.target.tagName==='SELECT')clear();});form.addEventListener('reset',()=>{clear();setTimeout(()=>{status.textContent='示例已恢复，等待生成';},0);});
 form.addEventListener('submit',e=>{e.preventDefault();clear();try{result.textContent=algorithms[form.dataset.pressTool]();copy.disabled=false;status.textContent='校样已生成';}catch(problem){error.textContent=problem.message;status.textContent='请检查输入';const field=form.elements.namedItem(problem.field);if(field){field.setAttribute('aria-invalid','true');field.setAttribute('aria-errormessage','bg70-error');field.focus();}}});
 copy.addEventListener('click',async()=>{if(copy.disabled)return;const current=revision,value=result.textContent;try{await navigator.clipboard.writeText(value);if(current===revision)copyStatus.textContent='完整报告已复制。';}catch{if(current===revision)copyStatus.textContent='剪贴板不可用，请在结果区域手动选择复制。';}});
})();
