(function consoleRuntime(){
 'use strict';const root=document.documentElement;root.classList.add('sl66-script');
 const toggle=document.querySelector('[data-signal-toggle]'),key='signal-uptime-066-theme',theme=value=>{const next=value==='light'?'light':'dark';root.dataset.signal=next;toggle.textContent=next==='light'?'暗台':'亮台';toggle.setAttribute('aria-label',next==='light'?'切换到暗台主题':'切换到亮台主题')};toggle.hidden=false;try{theme(localStorage.getItem(key))}catch{theme('dark')}toggle.addEventListener('click',()=>{theme(root.dataset.signal==='dark'?'light':'dark');try{localStorage.setItem(key,root.dataset.signal)}catch{}});
 const menu=document.querySelector('#sl66-menu'),button=document.querySelector('#sl66-menu-button');button.hidden=false;const close=(focus=false)=>{menu.classList.remove('sl66-open');button.setAttribute('aria-expanded','false');if(focus)button.focus()};button.addEventListener('click',()=>{const open=!menu.classList.contains('sl66-open');menu.classList.toggle('sl66-open',open);button.setAttribute('aria-expanded',String(open));if(open)menu.querySelector('a').focus()});menu.addEventListener('click',e=>{if(e.target.closest('a'))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.classList.contains('sl66-open'))close(true)});window.addEventListener('resize',()=>{if(innerWidth>940)close()});
 const code=document.querySelector('[data-copy-code]');if(code){code.disabled=false;code.addEventListener('click',async()=>{code.disabled=true;const state=document.querySelector('[data-code-state]');try{await navigator.clipboard.writeText(document.getElementById('sl66-code').textContent.trim());state.textContent='代码已复制。'}catch{state.textContent='浏览器未允许复制，请手动选择代码。'}finally{code.disabled=false}})}
 const progress=document.querySelector('[data-reading-progress]');if(progress){const update=()=>{const distance=root.scrollHeight-innerHeight;progress.style.width=(distance>0?Math.min(100,Math.max(0,scrollY/distance*100)):100)+'%'};update();document.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update)}
 const normal=s=>s.normalize('NFKC').trim().toLowerCase(),filter=document.querySelector('[data-trace-filter]');
 if(filter){filter.hidden=false;const items=[...document.querySelectorAll('[data-trace-bus]')],run=()=>{let n=0;for(const item of items){item.hidden=!(normal(item.querySelector('a b').textContent).includes(normal(filter.elements.keyword.value))&&(filter.elements.bus.value==='all'||filter.elements.bus.value===item.dataset.traceBus));if(!item.hidden)n++}filter.querySelector('[data-filter-state]').textContent='当前接入 '+n+' 份观察记录。'};filter.addEventListener('input',run);filter.addEventListener('change',run);filter.addEventListener('submit',e=>e.preventDefault());filter.addEventListener('reset',()=>setTimeout(run,0));run()}
 const search=document.querySelector('[data-local-search]');if(search){const items=[...document.querySelectorAll('[data-search-item]')],state=search.querySelector('[data-search-state]');search.querySelector('button').disabled=false;search.addEventListener('submit',e=>{e.preventDefault();const q=normal(search.elements.query.value);let n=0;for(const item of items){item.hidden=!normal(item.textContent).includes(q);if(!item.hidden)n++}state.textContent='找到 '+n+' 个本站入口。'});search.addEventListener('input',()=>{for(const item of items)item.hidden=false;state.textContent='输入已变化，请重新检索。'})}
})();
