(function chartRuntime(){
 'use strict';const root=document.documentElement;root.classList.add('cn67-script');
 const toggle=document.querySelector('[data-chart-toggle]'),key='midnight-constellation-067-chart',theme=value=>{const next=value==='night'?'night':'paper';root.dataset.chart=next;toggle.textContent=next==='night'?'纸图':'墨夜';toggle.setAttribute('aria-label',next==='night'?'切换到纸图主题':'切换到墨夜主题')};toggle.hidden=false;try{theme(localStorage.getItem(key))}catch{theme('paper')}toggle.addEventListener('click',()=>{theme(root.dataset.chart==='paper'?'night':'paper');try{localStorage.setItem(key,root.dataset.chart)}catch{}});
 const menu=document.querySelector('#cn67-menu'),button=document.querySelector('#cn67-menu-button');button.hidden=false;const close=(focus=false)=>{menu.classList.remove('cn67-open');button.setAttribute('aria-expanded','false');if(focus)button.focus()};button.addEventListener('click',()=>{const open=!menu.classList.contains('cn67-open');menu.classList.toggle('cn67-open',open);button.setAttribute('aria-expanded',String(open));if(open)menu.querySelector('a').focus()});menu.addEventListener('click',e=>{if(e.target.closest('a'))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.classList.contains('cn67-open'))close(true)});window.addEventListener('resize',()=>{if(innerWidth>900)close()});
 const code=document.querySelector('[data-copy-code]');if(code){code.disabled=false;code.addEventListener('click',async()=>{code.disabled=true;const state=document.querySelector('[data-code-state]');try{await navigator.clipboard.writeText(document.getElementById('cn67-code').textContent.trim());state.textContent='代码已复制。'}catch{state.textContent='浏览器未允许复制，请手动选择代码。'}finally{code.disabled=false}})}
 const progress=document.querySelector('[data-reading-progress]');if(progress){const update=()=>{const total=root.scrollHeight-innerHeight;progress.style.width=(total>0?Math.min(100,Math.max(0,scrollY/total*100)):100)+'%'};update();document.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update)}
 const normal=s=>s.normalize('NFKC').trim().toLowerCase(),filter=document.querySelector('[data-plate-filter]');
 if(filter){filter.hidden=false;const items=[...document.querySelectorAll('[data-plate-sector]')],run=()=>{let n=0;for(const item of items){item.hidden=!(normal(item.querySelector('a b').textContent).includes(normal(filter.elements.keyword.value))&&(filter.elements.sector.value==='all'||filter.elements.sector.value===item.dataset.plateSector));if(!item.hidden)n++}filter.querySelector('[data-filter-state]').textContent='已展开 '+n+' 张图版。'};filter.addEventListener('input',run);filter.addEventListener('change',run);filter.addEventListener('submit',e=>e.preventDefault());filter.addEventListener('reset',()=>setTimeout(run,0));run()}
 const search=document.querySelector('[data-local-search]');if(search){const items=[...document.querySelectorAll('[data-search-item]')],state=search.querySelector('[data-search-state]');search.querySelector('button').disabled=false;search.addEventListener('submit',e=>{e.preventDefault();const q=normal(search.elements.query.value);let n=0;for(const item of items){item.hidden=!normal(item.textContent).includes(q);if(!item.hidden)n++}state.textContent='找到 '+n+' 个本站入口。'});search.addEventListener('input',()=>{for(const item of items)item.hidden=false;state.textContent='输入已变化，请重新检索。'})}
})();
