(function(){
  "use strict";
  var root=document.documentElement;
  function fallbackCopy(value){var box=document.createElement("textarea");box.value=value;box.setAttribute("readonly","");box.style.position="fixed";box.style.opacity="0";document.body.appendChild(box);box.select();var ok=false;try{ok=document.execCommand("copy");}catch(_){ok=false;}box.remove();return ok;}
  function copyText(value){if(navigator.clipboard&&navigator.clipboard.writeText){return navigator.clipboard.writeText(value).then(function(){return true;},function(){return fallbackCopy(value);});}return Promise.resolve(fallbackCopy(value));}
  var inkToggle=document.querySelector("[data-gaz-ink-toggle]");
  var saved=null;try{saved=localStorage.getItem("north-gazette-ink");}catch(_){saved=null;}
  if(saved==="night")root.setAttribute("data-gaz-ink","night");
  function syncInk(){if(!inkToggle)return;var night=root.getAttribute("data-gaz-ink")==="night";inkToggle.setAttribute("aria-pressed",String(night));var label=inkToggle.querySelector("b");if(label)label.textContent=night?"日读":"夜读";}
  syncInk();
  if(inkToggle)inkToggle.addEventListener("click",function(){var next=root.getAttribute("data-gaz-ink")==="night"?"day":"night";root.setAttribute("data-gaz-ink",next);try{localStorage.setItem("north-gazette-ink",next);}catch(_){}syncInk();});
  var codeCopy=document.querySelector("[data-gaz-code-copy]");
  if(codeCopy)codeCopy.addEventListener("click",function(){var source=document.querySelector("[data-gaz-code]");var status=document.querySelector("[data-gaz-code-status]");copyText(source?source.textContent.trim():"").then(function(ok){if(status)status.textContent=ok?"邀请码已复制":"复制失败，请手动选择";});});
  function raw(form,name){return String(form.elements[name].value||"").trim();}
  function sourceTool(form){var value=raw(form,"sourceLines");if(!value)throw new Error("请至少输入一行来源。");var lines=value.split(/\r?\n/).map(function(line){return line.trim();}).filter(Boolean);if(lines.length>500)throw new Error("一次最多处理 500 行。");var sensitive=form.elements.caseSensitive.checked;var seen=new Map();lines.forEach(function(line){var key=sensitive?line:line.toLocaleLowerCase();if(!seen.has(key))seen.set(key,line);});var output=Array.from(seen.values()).sort(function(a,b){return a.localeCompare(b,"zh-Hans-CN",{sensitivity:sensitive?"variant":"base",numeric:true});});if(form.elements.direction.value==="desc")output.reverse();return "输入行数："+lines.length+"\n去重后："+output.length+"\n\n"+output.join("\n");}
  function datelineTool(form){var stamp=raw(form,"stamp");var offsetRaw=raw(form,"offset");if(!stamp||offsetRaw==="")throw new Error("请完整填写当地日期、时间与 UTC 偏移。");var offset=Number(offsetRaw);if(!Number.isFinite(offset)||offset< -12||offset>14||Math.round(offset*4)!==offset*4)throw new Error("UTC 偏移须为 -12 至 +14 之间的 0.25 小时间隔。");var match=stamp.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/);if(!match)throw new Error("日期时间格式无效。");var values=match.slice(1).map(Number);var localUtc=Date.UTC(values[0],values[1]-1,values[2],values[3],values[4]);var probe=new Date(localUtc);if(probe.getUTCFullYear()!==values[0]||probe.getUTCMonth()!==values[1]-1||probe.getUTCDate()!==values[2]||probe.getUTCHours()!==values[3]||probe.getUTCMinutes()!==values[4])throw new Error("日期时间不存在，请重新检查。");var utc=new Date(localUtc-offset*3600000);var sign=offset>=0?"+":"-";var abs=Math.abs(offset);var hours=String(Math.floor(abs)).padStart(2,"0");var minutes=String(Math.round((abs-Math.floor(abs))*60)).padStart(2,"0");return "原始日期线："+stamp+" UTC"+sign+hours+":"+minutes+"\nISO UTC："+utc.toISOString()+"\nUnix 秒："+Math.floor(utc.getTime()/1000);}
  function quoteTool(form){var value=raw(form,"copy");if(!value)throw new Error("请输入需要检查的文字。");if(Array.from(value).length>5000)throw new Error("一次最多检查 5,000 个字符。");var ascii=(value.match(/"/g)||[]).length;var leftDouble=(value.match(/“/g)||[]).length;var rightDouble=(value.match(/”/g)||[]).length;var leftSingle=(value.match(/‘/g)||[]).length;var rightSingle=(value.match(/’/g)||[]).length;var stack=[];var mismatch=0;Array.from(value).forEach(function(char){if(char==="“"||char==="‘")stack.push(char);if(char==="”"){if(stack.pop()!=="“")mismatch++;}if(char==="’"){if(stack.pop()!=="‘")mismatch++;}});var balanced=ascii%2===0&&leftDouble===rightDouble&&leftSingle===rightSingle&&stack.length===0&&mismatch===0;return "检查结论："+(balanced?"引号数量平衡":"发现不平衡，请人工核对")+"\nASCII 双引号："+ascii+"\n中文双引号："+leftDouble+" / "+rightDouble+"\n中文单引号："+leftSingle+" / "+rightSingle;}
  function headlineMetrics(value){var chars=Array.from(value.replace(/\s/g,"")).length;var punctuation=(value.match(/[，。！？：；、,.!?:;]/g)||[]).length;var clauses=punctuation+1;var band=chars<=12?"短讯型":chars<=24?"标准型":chars<=38?"长标题型":"需压缩";return {chars:chars,punctuation:punctuation,clauses:clauses,band:band};}
  function headlineTool(form){var a=raw(form,"headlineA"),b=raw(form,"headlineB");if(!a||!b)throw new Error("请完整填写两个标题版本。");if(Array.from(a).length>120||Array.from(b).length>120)throw new Error("每个标题最多 120 个字符。");var ma=headlineMetrics(a),mb=headlineMetrics(b);var delta=Math.abs(ma.chars-mb.chars);var note=ma.chars===mb.chars?"两版字数相同":ma.chars<mb.chars?"A 版更精简":"B 版更精简";return "A｜"+ma.chars+" 字符｜"+ma.clauses+" 分句｜"+ma.band+"\nB｜"+mb.chars+" 字符｜"+mb.clauses+" 分句｜"+mb.band+"\n差值："+delta+" 字符；"+note+"。\n提示：结果仅比较结构，不判断事实与语义质量。";}
  function diffTool(form){var oldRaw=raw(form,"oldText"),newRaw=raw(form,"newText");if(!oldRaw&&!newRaw)throw new Error("请至少填写一个版本。");var oldLines=oldRaw?oldRaw.split(/\r?\n/):[];var newLines=newRaw?newRaw.split(/\r?\n/):[];if(oldLines.length>200||newLines.length>200)throw new Error("每个版本最多 200 行。");var rows=oldLines.length+1,cols=newLines.length+1,table=Array.from({length:rows},function(){return Array(cols).fill(0);});var i,j;for(i=oldLines.length-1;i>=0;i--){for(j=newLines.length-1;j>=0;j--){table[i][j]=oldLines[i]===newLines[j]?table[i+1][j+1]+1:Math.max(table[i+1][j],table[i][j+1]);}}var out=[],added=0,removed=0,same=0;i=0;j=0;while(i<oldLines.length&&j<newLines.length){if(oldLines[i]===newLines[j]){out.push("= "+oldLines[i]);same++;i++;j++;}else if(table[i+1][j]>=table[i][j+1]){out.push("- "+oldLines[i]);removed++;i++;}else{out.push("+ "+newLines[j]);added++;j++;}}while(i<oldLines.length){out.push("- "+oldLines[i++]);removed++;}while(j<newLines.length){out.push("+ "+newLines[j++]);added++;}return "保留 "+same+" 行｜新增 "+added+" 行｜删除 "+removed+" 行\n\n"+out.join("\n");}
  function calculate(form){var mode=form.getAttribute("data-gaz-tool");if(mode==="source")return sourceTool(form);if(mode==="dateline")return datelineTool(form);if(mode==="quotes")return quoteTool(form);if(mode==="headline")return headlineTool(form);return diffTool(form);}
  document.querySelectorAll("form[data-gaz-tool]").forEach(function(form){var output=form.querySelector(".gaz-tool-output"),copy=form.querySelector("[data-gaz-copy]");function render(value,error){output.textContent=value;output.setAttribute("data-state",error?"error":"ready");copy.disabled=error||!value;}form.addEventListener("submit",function(event){event.preventDefault();try{render(calculate(form),false);}catch(error){render(error.message,true);}});form.addEventListener("reset",function(){window.setTimeout(function(){output.textContent="";output.removeAttribute("data-state");copy.disabled=true;},0);});copy.addEventListener("click",function(){copyText(output.textContent.trim()).then(function(ok){var old=copy.textContent;copy.textContent=ok?"已复制":"请手动复制";window.setTimeout(function(){copy.textContent=old;},1200);});});});
}());
