(function(){
  "use strict";
  function value(form,name,label){var raw=String(form.elements[name].value||"").trim();if(raw==="")throw new Error(label+"：%ERROR_REQUIRED%");var number=Number(raw);if(!Number.isFinite(number))throw new Error(label+"：%ERROR_NUMBER%");return number;}
  function periods(form,name,label,max,allowZero){var number=value(form,name,label);if(!Number.isInteger(number)||number<(allowZero?0:1)||number>max)throw new Error("%ERROR_PERIOD_RANGE%");return number;}
  function fmt(number,digits){return new Intl.NumberFormat("zh-CN",{maximumFractionDigits:digits===undefined?4:digits}).format(number);}
  function bounded(number){if(!Number.isFinite(number)||Math.abs(number)>1e15)throw new Error("%ERROR_DISPLAY_RANGE%");return number;}
  function growth(form){var p=value(form,"principal","%TOOL_01_FIELD_01%"),r=value(form,"rate","%TOOL_01_FIELD_02%"),n=periods(form,"periods","%TOOL_01_FIELD_03%",1000,false);if(p<=0||r<=-100||r>1000)throw new Error("%TOOL_01_ERROR_RANGE%");var end=bounded(p*Math.pow(1+r/100,n));return "%TOOL_01_RESULT_END%："+fmt(end)+"\n%TOOL_01_RESULT_CHANGE%："+fmt(end-p)+"\n%TOOL_01_RESULT_FACTOR%："+fmt(end/p,6);}
  function cadence(form){var a=value(form,"amount","%TOOL_02_FIELD_01%"),r=value(form,"rate","%TOOL_02_FIELD_02%"),n=periods(form,"periods","%TOOL_02_FIELD_03%",600,false);if(a<=0||r<=-100||r>1000)throw new Error("%TOOL_02_ERROR_RANGE%");var f=1+r/100,end=0,start=0;for(var i=0;i<n;i+=1){end=bounded(end*f+a);start=bounded((start+a)*f);}return "%TOOL_02_RESULT_END%："+fmt(end)+"\n%TOOL_02_RESULT_START%："+fmt(start)+"\n%TOOL_02_RESULT_GAP%："+fmt(start-end);}
  function drag(form){var p=value(form,"principal","%TOOL_03_FIELD_01%"),g=value(form,"grossRate","%TOOL_03_FIELD_02%"),fee=value(form,"feeRate","%TOOL_03_FIELD_03%"),n=periods(form,"periods","%TOOL_03_FIELD_04%",600,false);if(p<=0||g<=-100||g>1000||fee<0||fee>100)throw new Error("%TOOL_03_ERROR_RANGE%");var gross=bounded(p*Math.pow(1+g/100,n)),netRate=g-fee;if(netRate<=-100)throw new Error("%TOOL_03_ERROR_NET%");var net=bounded(p*Math.pow(1+netRate/100,n));return "%TOOL_03_RESULT_GROSS%："+fmt(gross)+"\n%TOOL_03_RESULT_NET%："+fmt(net)+"\n%TOOL_03_RESULT_DRAG%："+fmt(gross-net);}
  function real(form){var future=value(form,"future","%TOOL_04_FIELD_01%"),inflation=value(form,"inflation","%TOOL_04_FIELD_02%"),n=periods(form,"periods","%TOOL_04_FIELD_03%",1000,true);if(future<0||inflation<=-100||inflation>1000)throw new Error("%TOOL_04_ERROR_RANGE%");var present=bounded(future/Math.pow(1+inflation/100,n));return "%TOOL_04_RESULT_REAL%："+fmt(present)+"\n%TOOL_04_RESULT_GAP%："+fmt(future-present)+"\n%TOOL_04_RESULT_FACTOR%："+fmt(Math.pow(1+inflation/100,n),6);}
  function target(form){var start=value(form,"start","%TOOL_05_FIELD_01%"),goal=value(form,"target","%TOOL_05_FIELD_02%"),n=periods(form,"periods","%TOOL_05_FIELD_03%",1000,false);if(start<=0||goal<=0)throw new Error("%TOOL_05_ERROR_RANGE%");var rate=(Math.pow(goal/start,1/n)-1)*100;if(!Number.isFinite(rate)||rate<=-100||rate>100000)throw new Error("%TOOL_05_ERROR_SOLUTION%");return "%TOOL_05_RESULT_RATE%："+fmt(rate,8)+"%\n%TOOL_05_RESULT_FACTOR%："+fmt(goal/start,6)+"\n%TOOL_05_RESULT_NOTE%";}
  function calculate(form){var kind=form.getAttribute("data-clay-tool");if(kind==="growth")return growth(form);if(kind==="cadence")return cadence(form);if(kind==="drag")return drag(form);if(kind==="real")return real(form);return target(form);}
  function fallback(value){var area=document.createElement("textarea");area.value=value;area.setAttribute("readonly","");area.style.position="fixed";area.style.opacity="0";document.body.appendChild(area);area.select();var ok=false;try{ok=document.execCommand("copy");}catch(_){ok=false;}area.remove();return ok;}
  function copy(value){if(window.clayCopy)return window.clayCopy(value);if(navigator.clipboard&&navigator.clipboard.writeText)return navigator.clipboard.writeText(value).then(function(){return true;},function(){return fallback(value);});return Promise.resolve(fallback(value));}
  document.querySelectorAll("form[data-clay-tool]").forEach(function(form){var output=form.parentElement.querySelector("[data-clay-output]"),error=form.querySelector("[data-clay-error]"),copyButton=form.parentElement.querySelector("[data-clay-result-copy]");function clearInvalid(){form.querySelectorAll("[aria-invalid=true]").forEach(function(field){field.removeAttribute("aria-invalid");});}form.addEventListener("submit",function(event){event.preventDefault();clearInvalid();error.textContent="";try{output.textContent=calculate(form);copyButton.disabled=false;}catch(problem){error.textContent=problem.message;output.textContent="%RESULT_ERROR%";copyButton.disabled=true;var first=Array.prototype.find.call(form.elements,function(field){return field.matches&&field.matches("input")&&!String(field.value||"").trim();});if(first){first.setAttribute("aria-invalid","true");first.focus();}}});form.addEventListener("reset",function(){window.setTimeout(function(){clearInvalid();error.textContent="";output.textContent="%RESULT_IDLE%";copyButton.disabled=true;},0);});copyButton.addEventListener("click",function(){copy(output.textContent.trim()).then(function(ok){var label=copyButton.textContent;copyButton.textContent=ok?"%COPY_SUCCESS%":"%COPY_FAILURE%";window.setTimeout(function(){copyButton.textContent=label;},1200);});});});
}());
