(function(){
  "use strict";
  var root=document.documentElement;
  function legacyCopy(text){var field=document.createElement("textarea");field.value=text;field.setAttribute("readonly","");field.style.position="fixed";field.style.opacity="0";document.body.appendChild(field);field.select();var ok=false;try{ok=document.execCommand("copy");}catch(_){ok=false;}field.remove();return ok;}
  function copyText(text){if(navigator.clipboard&&navigator.clipboard.writeText){return navigator.clipboard.writeText(text).then(function(){return true;},function(){return legacyCopy(text);});}return Promise.resolve(legacyCopy(text));}
  var toggle=document.querySelector("[data-sr-theme-toggle]");var stored=null;try{stored=localStorage.getItem("sable-review-mode");}catch(_){stored=null;}if(stored==="dark")root.setAttribute("data-sr-theme","dark");
  function syncTheme(){if(!toggle)return;var dark=root.getAttribute("data-sr-theme")==="dark";toggle.setAttribute("aria-pressed",String(dark));var label=toggle.querySelector("span");if(label)label.textContent=dark?"展台":"暗房";}
  syncTheme();if(toggle)toggle.addEventListener("click",function(){var next=root.getAttribute("data-sr-theme")==="dark"?"ivory":"dark";root.setAttribute("data-sr-theme",next);try{localStorage.setItem("sable-review-mode",next);}catch(_){}syncTheme();});
  var codeButton=document.querySelector("[data-code-copy]");if(codeButton)codeButton.addEventListener("click",function(){var source=document.querySelector("[data-code-source]");var status=document.querySelector("[data-code-status]");copyText(source?source.textContent.trim():"").then(function(ok){if(status)status.textContent=ok?"邀请码已复制":"复制失败，请手动选择";});});
  function raw(form,name){return String(form.elements[name].value||"").trim();}
  function number(form,name){var value=raw(form,name);if(value==="")return NaN;var n=Number(value);return Number.isFinite(n)?n:NaN;}
  function calculate(form){var mode=form.getAttribute("data-lab");
    if(mode==="weighted"){var a=number(form,"a"),wa=number(form,"wa"),b=number(form,"b"),wb=number(form,"wb");if(![a,wa,b,wb].every(Number.isFinite))throw new Error("请完整填写得分与权重。");if(a<0||a>10||b<0||b>10)throw new Error("得分须在 0–10 之间。");if(wa<0||wb<0)throw new Error("权重不可为负数。");if(wa+wb===0)throw new Error("权重合计不可为 0。");var score=(a*wa+b*wb)/(wa+wb);return "加权结果："+score.toFixed(2)+" / 10\n归一化权重："+(wa/(wa+wb)*100).toFixed(1)+"% / "+(wb/(wa+wb)*100).toFixed(1)+"%";}
    if(mode==="consistency"){var values=raw(form,"scores").split(/[，,\s]+/).filter(Boolean).map(Number);if(values.length<2||!values.every(Number.isFinite))throw new Error("请至少输入两个有效评分。");if(values.some(function(v){return v<0||v>10;}))throw new Error("每个评分须在 0–10 之间。");var mean=values.reduce(function(s,v){return s+v;},0)/values.length;var variance=values.reduce(function(s,v){return s+Math.pow(v-mean,2);},0)/values.length;var min=Math.min.apply(null,values),max=Math.max.apply(null,values);return "平均值："+mean.toFixed(2)+"\n极差："+(max-min).toFixed(2)+"\n总体标准差："+Math.sqrt(variance).toFixed(3);}
    if(mode==="pairwise"){var nameA=raw(form,"nameA"),nameB=raw(form,"nameB"),winsA=number(form,"winsA"),winsB=number(form,"winsB"),ties=number(form,"ties");if(!nameA||!nameB)throw new Error("请填写两个对象名称。");if(![winsA,winsB,ties].every(Number.isInteger)||[winsA,winsB,ties].some(function(v){return v<0||v>20;}))throw new Error("维度数须为 0–20 的整数。");if(winsA+winsB+ties===0)throw new Error("至少需要一个比较维度。");var result=winsA===winsB?"未分胜负":winsA>winsB?nameA+" 暂时领先":nameB+" 暂时领先";return "比较结果："+result+"\n"+nameA+" 胜出："+winsA+"\n"+nameB+" 胜出："+winsB+"\n平局："+ties;}
    if(mode==="margin"){var sample=number(form,"sample"),p=number(form,"proportion"),z=number(form,"z");if(!Number.isInteger(sample)||sample<2||sample>10000000)throw new Error("样本量须为 2–10,000,000 的整数。");if(!Number.isFinite(p)||p<0||p>100)throw new Error("观察比例须在 0–100% 之间。");var ratio=p/100;var moe=z*Math.sqrt(ratio*(1-ratio)/sample)*100;return "近似误差范围：±"+moe.toFixed(2)+" 个百分点\n参考区间："+Math.max(0,p-moe).toFixed(2)+"% – "+Math.min(100,p+moe).toFixed(2)+"%\n提示：简单随机样本假设下的正态近似。";}
    var cost=number(form,"cost"),features=number(form,"features"),months=number(form,"months");if(!Number.isFinite(cost)||cost<0)throw new Error("总成本须为不小于 0 的数值。");if(!Number.isInteger(features)||features<1||features>100000)throw new Error("有效功能数须为 1–100,000 的整数。");if(!Number.isInteger(months)||months<1||months>1200)throw new Error("使用周期须为 1–1,200 月的整数。");return "每项功能成本："+(cost/features).toFixed(2)+"\n每月成本："+(cost/months).toFixed(2)+"\n每项功能每月："+(cost/features/months).toFixed(4);}
  document.querySelectorAll("form[data-lab]").forEach(function(form){var output=form.querySelector(".sr-lab-output"),copy=form.querySelector("[data-lab-copy]");function render(text,failed){output.textContent=text;output.setAttribute("data-state",failed?"error":"ready");copy.disabled=failed||!text;}form.addEventListener("submit",function(event){event.preventDefault();try{render(calculate(form),false);}catch(error){render(error.message,true);}});form.addEventListener("reset",function(){window.setTimeout(function(){output.textContent="";output.removeAttribute("data-state");copy.disabled=true;},0);});copy.addEventListener("click",function(){copyText(output.textContent.trim()).then(function(ok){var label=copy.textContent;copy.textContent=ok?"已复制":"请手动复制";window.setTimeout(function(){copy.textContent=label;},1200);});});});
}());
