(function(){
  "use strict";
  var root=document.documentElement;
  root.classList.add("mp76-enhanced");
  var themeButton=document.querySelector("[data-mp76-ink-toggle]"),themeKey="mp76-ink";
  function savedTheme(){try{return localStorage.getItem(themeKey)==="reverse"?"reverse":"black";}catch(_){return"black";}}
  function setTheme(value,remember){var next=value==="reverse"?"reverse":"black";root.dataset.mp76Ink=next;if(themeButton){themeButton.disabled=false;themeButton.setAttribute("aria-pressed",next==="reverse"?"true":"false");themeButton.textContent=next==="reverse"?"原稿黑":"反白";}if(remember)try{localStorage.setItem(themeKey,next);}catch(_){}}
  setTheme(savedTheme(),false);
  if(themeButton)themeButton.addEventListener("click",function(){setTheme(root.dataset.mp76Ink==="reverse"?"black":"reverse",true);});
  var menuButton=document.querySelector(".mp76-menu-button"),menu=document.getElementById("mp76-nav");
  function closeMenu(){if(!menuButton||!menu)return;menu.classList.remove("mp76-open");menuButton.setAttribute("aria-expanded","false");}
  if(menuButton&&menu){menuButton.addEventListener("click",function(){var open=menu.classList.toggle("mp76-open");menuButton.setAttribute("aria-expanded",open?"true":"false");if(open){var first=menu.querySelector("a");if(first)first.focus();}});menu.addEventListener("keydown",function(event){if(event.key==="Escape"){closeMenu();menuButton.focus();}});addEventListener("resize",function(){if(innerWidth>760)closeMenu();});}
  var progress=document.querySelector("[data-mp76-progress]");
  if(progress){var updateProgress=function(){var distance=document.documentElement.scrollHeight-innerHeight,amount=distance>0?Math.min(100,Math.max(0,scrollY/distance*100)):100;progress.style.width=amount.toFixed(2)+"%";};updateProgress();addEventListener("scroll",updateProgress,{passive:true});addEventListener("resize",updateProgress);}
  async function copy(value,status,success){try{await navigator.clipboard.writeText(value);status.textContent=success;}catch(_){status.textContent="未能复制，请手动选择文字。";}}
  function bindCopy(buttonSelector,textSelector,statusSelector){var button=document.querySelector(buttonSelector);if(!button)return;button.disabled=false;button.addEventListener("click",function(){var text=document.querySelector(textSelector),status=document.querySelector(statusSelector);copy(text.textContent.trim(),status,"已复制。");});}
  bindCopy("[data-mp76-copy-home]","#mp76-home-code","[data-mp76-home-status]");
  bindCopy("[data-mp76-copy-code]","#mp76-release-code","[data-mp76-code-status]");
  document.querySelectorAll("[data-mp76-filter]").forEach(function(form){form.hidden=false;var rows=[...document.querySelectorAll(".mp76-proof-list li")],status=form.querySelector("[data-mp76-filter-status]");function refresh(){var station=form.elements.station.value,word=form.elements.keyword.value.normalize("NFKC").trim().toLocaleLowerCase(),count=0;rows.forEach(function(row){row.hidden=!((station==="all"||row.dataset.mp76Station===station)&&row.textContent.normalize("NFKC").toLocaleLowerCase().includes(word));if(!row.hidden)count++;});status.textContent=count?"当前显示 "+count+" 张校样。":"没有匹配校样，请调整条件。";}form.addEventListener("input",refresh);form.addEventListener("change",refresh);form.addEventListener("reset",function(){setTimeout(refresh,0);});refresh();});
  function cp(value){return Array.from(value).length;}
  function malformed(value){for(var i=0;i<value.length;i++){var n=value.charCodeAt(i);if(n>=0xd800&&n<=0xdbff){if(i+1>=value.length||value.charCodeAt(i+1)<0xdc00||value.charCodeAt(i+1)>0xdfff)return true;i++;}else if(n>=0xdc00&&n<=0xdfff)return true;}return false;}
  function controls(value){return /[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f-\u009f]/.test(value);}
  function Problem(field,message){this.field=field;this.message=message;}
  function raw(form,name,max){var value=form.elements[name].value;if(cp(value)>max)throw new Problem(name,"原始输入最多 "+max+" 个 Unicode 码点。");if(malformed(value))throw new Problem(name,"输入包含不完整 Unicode，请重新输入。");if(controls(value))throw new Problem(name,"输入不能包含控制字符。");return value;}
  function lines(value){return value.normalize("NFKC").replace(/\r\n?/g,"\n").split("\n").map(function(text,index){return{number:index+1,text:text.trim()};}).filter(function(row){return row.text;});}
  function exactParts(row,count,field){var parts=row.text.split("|");if(parts.length!==count)throw new Problem(field,"第 "+row.number+" 行分隔符数量不正确。");return parts.map(function(x){return x.trim();});}
  function integer(value,min,max,field){if(!/^(?:0|[1-9]\d*)$/.test(value))throw new Problem(field,"请填写没有前导零的 ASCII 整数。");var n=Number(value);if(n<min||n>max)throw new Problem(field,"数值范围为 "+min+"–"+max+"。");return n;}
  function claims(form){var rows=lines(raw(form,"claims",15000));if(!rows.length||rows.length>100)throw new Problem("claims","需要 1–100 个非空陈述。");var seen=new Set(),fact=0,inference=0,items=rows.map(function(row){var p=exactParts(row,3,"claims"),statement=p[0],source=p[1],kind=p[2].toLocaleLowerCase(),key=statement.toLocaleLowerCase();if(!statement||cp(statement)>200)throw new Problem("claims","第 "+row.number+" 行陈述需为 1–200 个码点。");if(seen.has(key))throw new Problem("claims","陈述不能重复："+statement+"。");if(!/^[A-Za-z0-9._:-]{1,40}$/.test(source))throw new Problem("claims","第 "+row.number+" 行来源编号需为 1–40 个 ASCII 标识字符。");if(kind!=="fact"&&kind!=="inference")throw new Problem("claims","第 "+row.number+" 行类型只能是 fact 或 inference。");seen.add(key);kind==="fact"?fact++:inference++;return{row:row.number,statement:statement,source:source,kind:kind};}),report=["陈述来源套准表","陈述："+items.length+" · 事实："+fact+" · 推断："+inference,""];items.forEach(function(item,index){report.push((index+1)+". 原第 "+item.row+" 行 · "+item.kind.toUpperCase()+" · "+item.source,item.statement);});report.push("","边界：来源编号只核对映射完整性，不验证来源内容是否支持陈述。");return report.join("\n");}
  function dateValue(value,field){var m=/^(20\d{2})-(\d{2})-(\d{2})$/.exec(value);if(!m)throw new Problem(field,"日期必须是 2000–2099 的 YYYY-MM-DD。");var y=Number(m[1]),mo=Number(m[2]),d=Number(m[3]),ms=Date.UTC(y,mo-1,d),dt=new Date(ms);if(dt.getUTCFullYear()!==y||dt.getUTCMonth()!==mo-1||dt.getUTCDate()!==d)throw new Problem(field,"日期不是有效公历日期。");return ms;}
  function freshness(form){var rows=lines(raw(form,"dates",12000)),asText=raw(form,"asOf",10),asOf=dateValue(asText,"asOf");if(!rows.length||rows.length>100)throw new Problem("dates","需要 1–100 个非空日期条目。");var seen=new Set(),current=0,expired=0,future=0,items=rows.map(function(row){var p=exactParts(row,3,"dates"),name=p[0],key=name.toLocaleLowerCase();if(!name||cp(name)>100)throw new Problem("dates","第 "+row.number+" 行名称需为 1–100 个码点。");if(seen.has(key))throw new Problem("dates","条目不能重复："+name+"。");var checked=dateValue(p[1],"dates"),horizon=integer(p[2],0,3650,"dates"),age=(asOf-checked)/86400000,state=age<0?"未来日期":age<=horizon?"有效":"到期";seen.add(key);state==="有效"?current++:state==="到期"?expired++:future++;return{row:row.number,name:name,date:p[1],horizon:horizon,age:age,state:state};}),report=["核对日期保鲜窗","参考日："+asText+" · 条目："+items.length,"有效："+current+" · 到期："+expired+" · 未来日期："+future,""];items.forEach(function(item,index){report.push((index+1)+". 原第 "+item.row+" 行 · "+item.name+" · "+item.state,"核对 "+item.date+" · 间隔 "+item.age+" 天 · 窗口 "+item.horizon+" 天");});report.push("","方法：UTC 公历日毫秒差除以 86,400,000；未来日期单独标记。","边界：窗口由编辑定义，不代表信息真实或仍然适用。");return report.join("\n");}
  var wide=/[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}\p{Script=Hangul}\p{Emoji_Presentation}]/u;
  function halfText(n){return Math.floor(n/2)+"."+(n%2?"5":"0");}
  function headlines(form){var rows=lines(raw(form,"titles",15000)),width=integer(raw(form,"targetWidth",2),24,40,"targetWidth");if(![24,32,40].includes(width))throw new Problem("targetWidth","目标宽度必须为 24、32 或 40。");if(!rows.length||rows.length>80)throw new Problem("titles","需要 1–80 个非空标题。");var seen=new Set(),total=0,items=rows.map(function(row){var title=row.text.normalize("NFKC"),key=title.toLocaleLowerCase();if(cp(title)>200)throw new Problem("titles","原第 "+row.number+" 行标题最多 200 个码点。");if(seen.has(key))throw new Problem("titles","标题不能重复："+title+"。");var half=[...title].reduce(function(sum,ch){return sum+(/\s/u.test(ch)?1:wide.test(ch)?4:2);},0),needed=Math.max(1,Math.ceil(half/(width*2)));seen.add(key);total+=half;return{row:row.number,title:title,half:half,needed:needed};}),report=["标题视觉宽度尺","标题："+items.length+" · 目标："+width+" 单位 · 总视觉单位："+halfText(total),""];items.forEach(function(item,index){report.push((index+1)+". 原第 "+item.row+" 行 · "+halfText(item.half)+" 单位 · "+item.needed+" 行",item.title);});report.push("","模型：空格半单位，汉字、假名、韩文与 Emoji 两单位，其余码点一单位。","边界：这是编辑估算，不替代目标字体真实渲染。");return report.join("\n");}
  function plates(form){var rows=lines(raw(form,"plates",10000));if(!rows.length||rows.length>100)throw new Problem("plates","需要 1–100 个非空页面。");var seen=new Set(),counts={C:0,M:0,Y:0,K:0},items=rows.map(function(row){var p=exactParts(row,2,"plates"),name=p[0],key=name.toLocaleLowerCase(),list=p[1].split(",").map(function(x){return x.trim().toUpperCase();});if(!name||cp(name)>100)throw new Problem("plates","第 "+row.number+" 行页面名需为 1–100 个码点。");if(seen.has(key))throw new Problem("plates","页面名不能重复："+name+"。");if(!list.length||list.length>4||list.some(function(x){return !["C","M","Y","K"].includes(x);}))throw new Problem("plates","第 "+row.number+" 行只能使用 C、M、Y、K 色版。");if(new Set(list).size!==list.length)throw new Problem("plates","第 "+row.number+" 行色版不能重复。");seen.add(key);list.forEach(function(x){counts[x]++;});return{row:row.number,name:name,list:list};}),report=["页面色版叠印账","页面："+items.length+" · C "+counts.C+" · M "+counts.M+" · Y "+counts.Y+" · K "+counts.K,""];items.forEach(function(item,index){report.push((index+1)+". 原第 "+item.row+" 行 · "+item.name+" · "+item.list.join("+"));});report.push("","边界：只核对输入集合，不测量实际油墨、颜色或输出设备。");return report.join("\n");}
  function signoffs(form){var rows=lines(raw(form,"signoffs",15000));if(!rows.length||rows.length>100)throw new Problem("signoffs","需要 1–100 个非空签字项。");var map=new Map(),items=rows.map(function(row){var p=exactParts(row,3,"signoffs"),id=p[0],state=p[1].toLocaleLowerCase(),deps=p[2]==="-"?[]:p[2].split(",").map(function(x){return x.trim();});if(!/^[a-z][a-z0-9-]{0,39}$/.test(id))throw new Problem("signoffs","第 "+row.number+" 行编号须为小写 ASCII 标识。");if(map.has(id))throw new Problem("signoffs","编号不能重复："+id+"。");if(state!=="done"&&state!=="pending")throw new Problem("signoffs","第 "+row.number+" 行状态只能是 done 或 pending。");if(deps.some(function(x){return !/^[a-z][a-z0-9-]{0,39}$/.test(x);})||new Set(deps).size!==deps.length)throw new Problem("signoffs","第 "+row.number+" 行依赖编号无效或重复。");var item={row:row.number,id:id,state:state,deps:deps};map.set(id,item);return item;});items.forEach(function(item){item.deps.forEach(function(dep){if(dep===item.id)throw new Problem("signoffs",item.id+" 不能依赖自身。");if(!map.has(dep))throw new Problem("signoffs",item.id+" 的依赖不存在："+dep+"。");});});var color=new Map(),stack=[];function visit(id){var c=color.get(id)||0;if(c===1)throw new Problem("signoffs","依赖形成循环："+stack.concat(id).join(" → ")+"。");if(c===2)return;color.set(id,1);stack.push(id);map.get(id).deps.forEach(visit);stack.pop();color.set(id,2);}items.forEach(function(item){visit(item.id);});function blockers(item,seen){var found=[];item.deps.forEach(function(id){if(seen.has(id))return;seen.add(id);var dep=map.get(id);if(dep.state!=="done")found.push(id);found.push.apply(found,blockers(dep,seen));});return found;}var ready=0,result=items.map(function(item){var blocked=[...new Set(blockers(item,new Set()))],state=item.state==="done"&&!blocked.length?"SIGNED":"PENDING";if(state==="SIGNED")ready++;return{item:item,blocked:blocked,state:state};}),report=["签字依赖闸","项目："+items.length+" · 已签："+ready+" · 待处理："+(items.length-ready),""];result.forEach(function(x,index){report.push((index+1)+". 原第 "+x.item.row+" 行 · "+x.item.id+" · "+x.state,"自身："+x.item.state+" · 依赖："+(x.item.deps.join("、")||"无")+" · 阻塞："+(x.blocked.join("、")||"无"));});report.push("","方法：先检查存在性与有向环，再递归收集未完成祖先。","边界：状态来自输入，不代表实际审批或发布授权。");return report.join("\n");}
  var calculators=[claims,freshness,headlines,plates,signoffs];
  document.querySelectorAll("form[data-mp76-tool]").forEach(function(form){var index=Number(form.dataset.mp76Tool),output=document.querySelector("[data-tool-output]"),copyButton=document.querySelector("[data-copy-tool]"),copyStatus=document.querySelector("[data-copy-status]"),status=form.querySelector("[data-form-status]"),revision=0;form.querySelectorAll("button").forEach(function(button){button.disabled=false;});function invalidate(){revision++;output.textContent="";copyButton.disabled=true;copyStatus.textContent="";form.querySelectorAll("[aria-invalid]").forEach(function(field){field.removeAttribute("aria-invalid");field.removeAttribute("aria-errormessage");});form.querySelectorAll("[data-field-error]").forEach(function(note){note.textContent="";});status.textContent="输入已变化，请重新生成报告。";}form.addEventListener("input",invalidate);form.addEventListener("change",invalidate);form.addEventListener("submit",function(event){event.preventDefault();invalidate();try{output.textContent=calculators[index](form);copyButton.disabled=false;status.textContent="计算完成，完整报告在右侧或下方。";}catch(error){var field=error.field&&form.elements[error.field],note=error.field&&form.querySelector('[data-field-error="'+error.field+'"]');if(field&&note){note.textContent=error.message;field.setAttribute("aria-invalid","true");field.setAttribute("aria-errormessage",note.id);field.focus();status.textContent="输入未通过校验，请检查标记字段。";}else status.textContent="暂时无法生成报告，请刷新后重试。";}});form.addEventListener("reset",function(){invalidate();setTimeout(function(){output.textContent="等待有效输入。";status.textContent="已恢复示例，请重新生成报告。";},0);});copyButton.addEventListener("click",async function(){if(copyButton.disabled||!output.textContent)return;var at=revision,value=output.textContent;try{await navigator.clipboard.writeText(value);if(at===revision)copyStatus.textContent="完整报告已复制。";}catch(_){if(at===revision)copyStatus.textContent="未能复制，请手动选择报告。";}});});
  var search=document.querySelector("[data-mp76-search]");
  if(search){var button=search.querySelector("button"),result=search.querySelector("[data-mp76-search-result]"),routes=[...[...document.querySelectorAll("#mp76-nav a")].map(function(a){return{label:a.textContent,href:a.getAttribute("href")};}),{label:"取证台",href:"stations/evidence-table.html"},{label:"文字台",href:"stations/language-booth.html"},{label:"版式墙",href:"stations/layout-wall.html"},{label:"签印门",href:"stations/release-gate.html"}];button.disabled=false;function refresh(){var query=search.elements.query.value.normalize("NFKC").trim().toLocaleLowerCase();result.replaceChildren();var hits=query?routes.filter(function(route){return route.label.toLocaleLowerCase().includes(query);}):routes.slice(0,4);if(!hits.length){result.textContent="没有匹配入口，请换一个关键词。";return;}result.append("可前往：");hits.forEach(function(route){var a=document.createElement("a");a.href=route.href;a.textContent=route.label;result.appendChild(a);});}search.addEventListener("submit",function(event){event.preventDefault();refresh();});search.addEventListener("input",function(){result.textContent="关键词已变化，提交后重新检索。";});refresh();}
})();
