(function(){"use strict";
var root=document.documentElement,themeButton=document.querySelector("[data-mp76-ink-toggle]"),themeKey="mp76-ink";
function getTheme(){try{return localStorage.getItem(themeKey)==="reverse"?"reverse":"black"}catch(error){return"black"}}
function setTheme(value,remember){var next=value==="reverse"?"reverse":"black";root.setAttribute("data-mp76-ink",next);if(themeButton){themeButton.setAttribute("aria-pressed",next==="reverse"?"true":"false");themeButton.textContent=next==="reverse"?"原稿黑":"反白"}if(remember)try{localStorage.setItem(themeKey,next)}catch(error){}}
setTheme(getTheme(),false);if(themeButton)themeButton.addEventListener("click",function(){setTheme(root.getAttribute("data-mp76-ink")==="reverse"?"black":"reverse",true)});
var menuButton=document.querySelector(".mp76-menu-button"),menu=document.getElementById("mp76-nav");
function closeMenu(){if(!menuButton||!menu)return;menu.classList.remove("mp76-open");menuButton.setAttribute("aria-expanded","false")}
if(menuButton&&menu){menuButton.addEventListener("click",function(){var open=menu.classList.toggle("mp76-open");menuButton.setAttribute("aria-expanded",open?"true":"false");if(open){var first=menu.querySelector("a");if(first)first.focus()}});menu.addEventListener("keydown",function(event){if(event.key==="Escape"){closeMenu();menuButton.focus()}});window.addEventListener("resize",function(){if(innerWidth>760)closeMenu()})}
var progress=document.querySelector("[data-mp76-progress]");if(progress){var updateProgress=function(){var distance=document.documentElement.scrollHeight-innerHeight,amount=distance>0?Math.min(100,Math.max(0,scrollY/distance*100)):100;progress.style.width=amount.toFixed(2)+"%"};updateProgress();addEventListener("scroll",updateProgress,{passive:true});addEventListener("resize",updateProgress)}
function copyText(text,status,message){if(!navigator.clipboard||!navigator.clipboard.writeText){status.textContent="当前浏览器不支持自动复制，请手动选择文字。";return}navigator.clipboard.writeText(text).then(function(){status.textContent=message}).catch(function(){status.textContent="复制未完成，请允许剪贴板权限后重试。"})}
var handoff=document.querySelector("[data-mp76-copy-handoff]");if(handoff)handoff.addEventListener("click",function(){copyText("编辑签字清单\n1. 直接来源能够支持对应陈述\n2. 会变化的信息标注核对日期\n3. 结论旁写明适用范围\n4. 推断列出前提和其他可能",document.querySelector("[data-mp76-handoff-status]"),"签字清单已复制。")});
var disclosureButton=document.querySelector("[data-mp76-copy-disclosure]");if(disclosureButton)disclosureButton.addEventListener("click",function(){var text=document.querySelector("[data-mp76-disclosure]");copyText(text?text.textContent.trim():"",document.querySelector("[data-mp76-disclosure-status]"),"简短披露已复制。")});
var form=document.querySelector("[data-mp76-title-form]");if(form){var input=document.getElementById("mp76-titles"),widthField=document.getElementById("mp76-width"),errorBox=document.querySelector("[data-mp76-title-error]"),statusBox=document.querySelector("[data-mp76-title-status]"),report=document.querySelector(".mp76-title-report"),state=document.querySelector("[data-mp76-title-state]"),countBox=document.querySelector("[data-mp76-title-count]"),unitBox=document.querySelector("[data-mp76-unit-total]"),longBox=document.querySelector("[data-mp76-long-count]"),list=document.querySelector("[data-mp76-title-list]"),note=document.querySelector("[data-mp76-title-note]"),copyButton=document.querySelector("[data-mp76-copy-report]"),copyStatus=document.querySelector("[data-mp76-report-status]"),lastReport=[];
var presets={mixed:"把来源、日期和范围放在结论旁边\nHow evidence changes a headline\n校样完成了吗？✓",short:"先看结论\n核对日期\n标出范围\n保留来源",long:"当多个来源对同一项规则给出互相冲突的解释时应该怎样记录证据与尚不能确认的部分"};
var wide=/[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}\p{Script=Hangul}\p{Emoji_Presentation}]/u;
function len(value){return Array.from(value).length}function visualUnits(value){var total=0;Array.from(value).forEach(function(char){if(/\s/u.test(char))total+=.5;else if(wide.test(char))total+=2;else total+=1});return total}
function invalidate(){if(report.getAttribute("data-ready")==="true"){report.setAttribute("data-ready","stale");state.textContent="RE-PROOF";statusBox.textContent="输入或宽度已变化，请重新生成校样。";copyButton.disabled=true}input.removeAttribute("aria-invalid");errorBox.textContent="";copyStatus.textContent=""}
function fail(message){input.setAttribute("aria-invalid","true");errorBox.textContent=message;statusBox.textContent="尚未生成校样。";input.focus();return null}
function parse(){var raw=input.value;if(len(raw)>2000)return fail("总输入不能超过 2,000 个 Unicode 字符。");var normalized=raw.normalize("NFKC"),lines=normalized.split(/\r?\n/).map(function(line){return line.trim().replace(/\s+/gu," ")}).filter(Boolean);if(!lines.length)return fail("请先输入至少一条标题。空白行会自动忽略。");if(lines.length>30)return fail("最多处理 30 条非空标题。");var seen=new Set(),items=[];for(var index=0;index<lines.length;index+=1){var title=lines[index];if(len(title)>120)return fail("第 "+(index+1)+" 条标题不能超过 120 个 Unicode 字符。");var key=title.toLocaleLowerCase();if(seen.has(key))return fail("标题不能重复："+title+"。");seen.add(key);items.push({title:title,units:visualUnits(title),index:index})}var width=Number(widthField.value);if(![24,32,40].includes(width))return fail("目标宽度必须是 24、32 或 40 单位。");return{items:items,width:width}}
function render(result){var total=0,long=0;list.replaceChildren();result.items.forEach(function(item,index){item.rows=Math.max(1,Math.ceil(item.units/result.width));total+=item.units;if(item.rows>2)long+=1;if(index<20){var row=document.createElement("li"),title=document.createElement("b"),meta=document.createElement("span"),flag=document.createElement("strong");title.textContent=item.title;meta.textContent=item.units.toFixed(1)+" 单位 · 目标 "+result.width;flag.textContent=item.rows+" 行";row.setAttribute("data-long",item.rows>2?"true":"false");row.append(title,meta,flag);list.appendChild(row)}});countBox.textContent=String(result.items.length);unitBox.textContent=total.toFixed(1);longBox.textContent=String(long);report.setAttribute("data-ready","true");state.textContent=long?"CHECK LONG":"PROOF OK";note.textContent=result.items.length>20?"显示前 20 条；复制报告包含全部 "+result.items.length+" 条。":"估算已完成；请在目标字体中做最终渲染复核。";statusBox.textContent="已校样 "+result.items.length+" 条标题，其中 "+long+" 条预计超过两行。";input.removeAttribute("aria-invalid");errorBox.textContent="";copyButton.disabled=false;lastReport=result.items.map(function(item){return item.title+"｜"+item.units.toFixed(1)+" 单位｜预计 "+item.rows+" 行"})}
form.addEventListener("submit",function(event){event.preventDefault();var result=parse();if(result)render(result)});input.addEventListener("input",invalidate);widthField.addEventListener("change",invalidate);document.querySelectorAll("[data-mp76-preset]").forEach(function(button){button.addEventListener("click",function(){input.value=presets[button.getAttribute("data-mp76-preset")];invalidate();input.focus()})});form.addEventListener("reset",function(){setTimeout(function(){report.setAttribute("data-ready","false");state.textContent="UNPROOFED";countBox.textContent="0";unitBox.textContent="0";longBox.textContent="0";list.replaceChildren(document.createElement("li"));list.firstElementChild.textContent="生成后显示前 20 条标题、视觉单位和预计行数。";note.textContent="估算用于编辑试排，不替代目标字体的真实渲染。";statusBox.textContent="工作台已清空。";errorBox.textContent="";copyStatus.textContent="";input.removeAttribute("aria-invalid");copyButton.disabled=true;lastReport=[];input.focus()},0)});copyButton.addEventListener("click",function(){if(!lastReport.length||report.getAttribute("data-ready")!=="true")return;copyText("标题视觉宽度校样\n"+lastReport.join("\n")+"\n说明：视觉单位是编辑估算，不替代真实字体渲染。",copyStatus,"标题校样报告已复制。")})}
var searchForm=document.querySelector("[data-mp76-search]");if(searchForm){var query=document.getElementById("mp76-query"),result=document.querySelector("[data-mp76-search-result]"),destinations=[{words:["来源","事实","解释","推断","文章","批注"],url:"article.html",label:"批注稿"},{words:["标题","宽度","工具","试排","校样尺"],url:"tool.html",label:"标题尺"},{words:["披露","隐私","说明","联系","更正","条款"],url:"legal.html",label:"印务说明"},{words:["首页","校样台","目录","期号"],url:"index.html",label:"校样台"}];searchForm.addEventListener("submit",function(event){event.preventDefault();var value=query.value.normalize("NFKC").trim();result.replaceChildren();if(!value){result.textContent="请输入一个主题，例如“来源”或“标题”。";query.focus();return}if(Array.from(value).length>80){result.textContent="查询不能超过 80 个 Unicode 字符。";query.focus();return}var hit=destinations.find(function(destination){return destination.words.some(function(word){return value.toLocaleLowerCase().includes(word)})});if(!hit){result.textContent="本地页码表没有匹配项。请缩短主题，或返回校样台。";return}result.append("找到最近的页面：");var link=document.createElement("a");link.href=hit.url;link.textContent=hit.label;result.appendChild(link)});query.addEventListener("input",function(){result.textContent="查询已变化，提交后重新检索本地页码表。"})}
})();
