(function(){
  "use strict";
  function num(form,name,label){var raw=String(form.elements[name].value||"").trim();if(raw==="")throw new Error(label+"：%ERROR_REQUIRED%");var value=Number(raw);if(!Number.isFinite(value))throw new Error(label+"：%ERROR_NUMBER%");return value;}
  function fmt(value,digits){return new Intl.NumberFormat("zh-CN",{maximumFractionDigits:digits===undefined?4:digits}).format(value);}
  function fee(form){var amount=num(form,"amount","%TOOL_01_FIELD_01%"),rate=num(form,"rate","%TOOL_01_FIELD_02%"),minimum=num(form,"minimum","%TOOL_01_FIELD_03%");if(amount<=0||rate<0||rate>100||minimum<0)throw new Error("%TOOL_01_ERROR_RANGE%");var raw=amount*rate/100,charged=Math.max(raw,minimum);return "%TOOL_01_RESULT_RAW%："+fmt(raw)+"\n%TOOL_01_RESULT_CHARGED%："+fmt(charged)+"\n%TOOL_01_RESULT_SHARE%："+fmt(charged/amount*100,6)+"%";}
  function breakeven(form){var entry=num(form,"entry","%TOOL_02_FIELD_01%"),buy=num(form,"buyRate","%TOOL_02_FIELD_02%"),sell=num(form,"sellRate","%TOOL_02_FIELD_03%");if(entry<=0||buy<0||sell<0||buy>25||sell>25)throw new Error("%TOOL_02_ERROR_RANGE%");var denominator=1-sell/100;if(denominator<=0)throw new Error("%TOOL_02_ERROR_DENOMINATOR%");var target=entry*(1+buy/100)/denominator;return "%TOOL_02_RESULT_PRICE%："+fmt(target,8)+"\n%TOOL_02_RESULT_CHANGE%："+fmt((target/entry-1)*100,6)+"%\n%TOOL_02_RESULT_NOTE%";}
  function allocation(form){var total=num(form,"total","%TOOL_03_FIELD_01%");if(total<=0)throw new Error("%TOOL_03_ERROR_TOTAL%");var raw=String(form.elements.weights.value||"").trim();if(!raw)throw new Error("%TOOL_03_ERROR_WEIGHTS%");var parts=raw.split(/[，,\n]+/).map(function(item){return Number(item.trim());});if(parts.length<2||parts.length>20||parts.some(function(value){return !Number.isFinite(value)||value<=0;}))throw new Error("%TOOL_03_ERROR_RANGE%");var sum=parts.reduce(function(a,b){return a+b;},0);return parts.map(function(weight,index){return "%TOOL_03_RESULT_ITEM% "+(index+1)+"："+fmt(total*weight/sum)+"（"+fmt(weight/sum*100,3)+"%）";}).join("\n");}
  function change(form){var oldValue=num(form,"oldValue","%TOOL_04_FIELD_01%"),newValue=num(form,"newValue","%TOOL_04_FIELD_02%");if(oldValue===0)throw new Error("%TOOL_04_ERROR_ZERO%");var delta=newValue-oldValue;return "%TOOL_04_RESULT_DELTA%："+(delta>=0?"+":"")+fmt(delta,8)+"\n%TOOL_04_RESULT_RATE%："+(delta/oldValue>=0?"+":"")+fmt(delta/Math.abs(oldValue)*100,6)+"%\n%TOOL_04_RESULT_DIRECTION%："+(delta>0?"%TOOL_04_UP%":delta<0?"%TOOL_04_DOWN%":"%TOOL_04_FLAT%");}
  function runway(form){var balance=num(form,"balance","%TOOL_05_FIELD_01%"),inflow=num(form,"inflow","%TOOL_05_FIELD_02%"),outflow=num(form,"outflow","%TOOL_05_FIELD_03%");if(balance<0||inflow<0||outflow<0)throw new Error("%TOOL_05_ERROR_RANGE%");var burn=outflow-inflow;if(burn<=0)return "%TOOL_05_RESULT_NON_BURN%\n%TOOL_05_RESULT_NET%："+fmt(inflow-outflow);var months=balance/burn;return "%TOOL_05_RESULT_MONTHS%："+fmt(months,2)+"\n%TOOL_05_RESULT_NET_BURN%："+fmt(burn)+"\n%TOOL_05_RESULT_DAYS%："+fmt(months*30.4375,0);}
  function calculate(form){var type=form.getAttribute("data-hld-tool");if(type==="fee")return fee(form);if(type==="breakeven")return breakeven(form);if(type==="allocation")return allocation(form);if(type==="change")return change(form);return runway(form);}
  function fallback(value){var area=document.createElement("textarea");area.value=value;area.setAttribute("readonly","");area.style.position="fixed";area.style.opacity="0";document.body.appendChild(area);area.select();var ok=false;try{ok=document.execCommand("copy");}catch(_){ok=false;}area.remove();return ok;}
  function copy(value){if(navigator.clipboard&&navigator.clipboard.writeText)return navigator.clipboard.writeText(value).then(function(){return true;},function(){return fallback(value);});return Promise.resolve(fallback(value));}
  document.querySelectorAll("form[data-hld-tool]").forEach(function(form){var output=form.parentElement.querySelector("[data-hld-output]");var error=form.querySelector("[data-hld-error]");var copyButton=form.parentElement.querySelector("[data-hld-result-copy]");function resetValidity(){form.querySelectorAll("[aria-invalid=true]").forEach(function(field){field.removeAttribute("aria-invalid");});}form.addEventListener("submit",function(event){event.preventDefault();resetValidity();error.textContent="";try{output.textContent=calculate(form);copyButton.disabled=false;}catch(problem){error.textContent=problem.message;output.textContent="%RESULT_ERROR%";copyButton.disabled=true;var empty=Array.prototype.find.call(form.elements,function(field){return field.matches&&field.matches("input,textarea")&&!String(field.value||"").trim();});if(empty){empty.setAttribute("aria-invalid","true");empty.focus();}}});form.addEventListener("reset",function(){window.setTimeout(function(){resetValidity();error.textContent="";output.textContent="%RESULT_IDLE%";copyButton.disabled=true;},0);});copyButton.addEventListener("click",function(){copy(output.textContent.trim()).then(function(ok){var original=copyButton.textContent;copyButton.textContent=ok?"%COPY_SUCCESS%":"%COPY_FAILURE%";window.setTimeout(function(){copyButton.textContent=original;},1200);});});});
}());
