(()=>{'use strict';
const root=document.documentElement;root.classList.add('pi71-enhanced');
const themeKey='plum-inbox-071-mail',toggle=document.querySelector('[data-mail-toggle]');
function setTheme(value){root.dataset.mail=value==='night'?'night':'cream';if(toggle){toggle.textContent=root.dataset.mail==='night'?'日档':'夜档';toggle.setAttribute('aria-label',root.dataset.mail==='night'?'切换到日间档案':'切换到夜间档案');}}
try{setTheme(localStorage.getItem(themeKey));}catch{setTheme('cream');}
if(toggle){toggle.disabled=false;toggle.addEventListener('click',()=>{setTheme(root.dataset.mail==='night'?'cream':'night');try{localStorage.setItem(themeKey,root.dataset.mail);}catch{}});}
const menu=document.querySelector('#pi71-menu'),menuButton=document.querySelector('#pi71-menu-button');
function closeMenu(focus=false){menu?.classList.remove('pi71-open');menuButton?.setAttribute('aria-expanded','false');if(focus)menuButton?.focus();}
menuButton?.addEventListener('click',()=>{const open=!menu.classList.contains('pi71-open');menu.classList.toggle('pi71-open',open);menuButton.setAttribute('aria-expanded',String(open));if(open)menu.querySelector('a')?.focus();});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&menu?.classList.contains('pi71-open'))closeMenu(true);});
document.addEventListener('click',event=>{if(menu?.classList.contains('pi71-open')&&!menu.contains(event.target)&&!menuButton.contains(event.target))closeMenu();});
menu?.addEventListener('click',event=>{if(event.target.closest('a'))closeMenu();});addEventListener('resize',()=>{if(innerWidth>960)closeMenu();});
async function copy(value){if(!navigator.clipboard||!isSecureContext)throw Error('clipboard unavailable');await navigator.clipboard.writeText(value);}
const codeButton=document.querySelector('[data-copy-code]');if(codeButton){codeButton.disabled=false;codeButton.addEventListener('click',async()=>{const state=document.querySelector('[data-code-state]');try{await copy(document.querySelector('#pi71-code').textContent.trim());state.textContent='代码已复制。';}catch{state.textContent='复制不可用，请手动选择代码。';}});}
const filter=document.querySelector('[data-letter-filter]');if(filter){filter.hidden=false;const rows=[...document.querySelectorAll('[data-letter-folder]')];const update=()=>{const folder=filter.elements.folder.value,query=filter.elements.keyword.value.normalize('NFKC').trim().toLowerCase();let count=0;for(const row of rows){row.hidden=!(folder==='all'||row.dataset.letterFolder===folder)||!row.querySelector('h3').textContent.normalize('NFKC').toLowerCase().includes(query);if(!row.hidden)count++;}filter.querySelector('[data-filter-state]').textContent='当前显示 '+count+' / '+rows.length+' 封信件。';};filter.addEventListener('input',update);filter.addEventListener('change',update);filter.addEventListener('reset',()=>setTimeout(update,0));update();}
const search=document.querySelector('[data-local-search]');if(search){search.querySelector('[type=submit]').disabled=false;const query=search.elements.query,rows=[...document.querySelectorAll('[data-search-item]')],state=search.querySelector('[data-search-state]');search.addEventListener('submit',event=>{event.preventDefault();const q=query.value.normalize('NFKC').trim().toLowerCase();let count=0;for(const row of rows){row.hidden=!row.textContent.normalize('NFKC').toLowerCase().includes(q);if(!row.hidden)count++;}state.textContent='找到 '+count+' 个入口。';});query.addEventListener('input',()=>{rows.forEach(row=>row.hidden=false);state.textContent='关键词已变化，提交后重新筛选。';});}
const progress=document.querySelector('[data-reading-progress]');if(progress){const update=()=>{const span=document.documentElement.scrollHeight-innerHeight;progress.style.width=(span>0?Math.min(100,Math.max(0,scrollY/span*100)):100)+'%';};addEventListener('scroll',update,{passive:true});addEventListener('resize',update);addEventListener('load',update);update();}
const form=document.querySelector('[data-sorter]');if(!form)return;
const report=document.querySelector('[data-result-text]'),copyButton=document.querySelector('[data-copy-result]'),copyState=document.querySelector('[data-result-copy-state]'),status=form.querySelector('[data-tool-state]');let revision=0;
form.querySelector('[type=submit]').disabled=false;
function clear(){revision++;report.textContent='';copyButton.disabled=true;copyState.textContent='';for(const e of form.querySelectorAll('[aria-invalid]')){e.removeAttribute('aria-invalid');e.removeAttribute('aria-errormessage');}for(const e of form.querySelectorAll('[data-field-error]'))e.textContent='';}
function invalid(field,message){const error=new Error(message);error.field=field;throw error;}
const length=s=>Array.from(s).length;
function raw(name){const value=form.elements[name].value;if(!value.isWellFormed()||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/u.test(value))invalid(name,'请移除不完整字符或控制符。');if(length(value)>10000)invalid(name,'整体最多允许 10000 个 Unicode 码点。');return value.replace(/\r\n?/g,'\n');}
function rows(name,max=100){const result=raw(name).split('\n').map((s,i)=>({value:s.normalize('NFKC').trim(),line:i+1})).filter(r=>r.value);if(!result.length)invalid(name,'请至少输入一条有效内容。');if(result.length>max)invalid(name,'最多允许 '+max+' 个非空行。');return result;}
function integer(name,min,max){const s=raw(name).trim();if(!/^[0-9]{1,10}$/.test(s))invalid(name,'请使用 '+min+'–'+max+' 范围内的 ASCII 整数。');const n=Number(s);if(n<min||n>max)invalid(name,'数字必须在 '+min+'–'+max+' 之间。');return n;}
function subjects(){const list=rows('subjects'),groups=new Map();let prefixed=0,prefixes=0;for(const r of list){let core=r.value.replace(/\s+/g,' '),depth=0;if(length(core)>180)invalid('subjects','第 '+r.line+' 行超过 180 码点。');const re=/^(?:re|fw|fwd|答复|回复|转发)\s*:\s*/i;while(re.test(core)){if(depth===20)invalid('subjects','第 '+r.line+' 行超过 20 层前缀。');core=core.replace(re,'').trim();depth++;}if(!core)invalid('subjects','第 '+r.line+' 行没有剩余主题。');if(depth)prefixed++;prefixes+=depth;const key=core.toLowerCase();if(!groups.has(key))groups.set(key,{core,rows:[],depth:0});const g=groups.get(key);g.rows.push(r.line);g.depth+=depth;}return ['主题行线程报告','主题行：'+list.length,'线程：'+groups.size,'含前缀行：'+prefixed,'剥离前缀：'+prefixes,'归并项：'+(list.length-groups.size),'',...[...groups.values()].map((g,i)=>(i+1)+'. '+g.core+' · '+g.rows.length+' 行 · 前缀 '+g.depth+' 次\n输入行：'+g.rows.join(', ')),'','相同核心不代表同一事件或邮件。'].join('\n');}
function enclosures(){const list=rows('enclosures'),limit=integer('limit',1,1024)*1048576,headers=integer('headers',0,1048576);let total=0,rawTotal=0;const details=list.map((r,i)=>{const parts=r.value.split('|').map(s=>s.trim());if(parts.length!==2||!parts[0]||length(parts[0])>80||!/^[0-9]{1,10}$/.test(parts[1]))invalid('enclosures','第 '+r.line+' 行需要 名称 | KiB；名称最多 80 码点。');const kib=Number(parts[1]);if(kib<1||kib>1048576)invalid('enclosures','第 '+r.line+' 行 KiB 必须为 1–1048576 的整数。');const bytes=kib*1024,chars=4*Math.ceil(bytes/3),breaks=2*Math.floor((chars-1)/76),sum=chars+breaks+headers;rawTotal+=bytes;total+=sum;return (i+1)+'. 第 '+r.line+' 行 · '+parts[0]+'\n原始 '+bytes+' 字节；Base64 '+chars+' 字符；折行 '+breaks+' 字节；额外 '+headers+' 字节\n估算 '+sum+' 字节';});return ['附件体积估算报告','附件：'+list.length,'原始合计：'+rawTotal+' 字节','编码估算合计：'+total+' 字节','整封上限：'+limit+' 字节',total<=limit?'剩余：'+(limit-total)+' 字节':'超出：'+(total-limit)+' 字节','',...details,'','不含正文与未指定开销；不能保证投递。'].join('\n');}
function time(name){const s=raw(name).trim();if(!/^(?:[01][0-9]|2[0-3]):[0-5][0-9]$/.test(s))invalid(name,'请填写有效 HH:mm 时刻。');return Number(s.slice(0,2))*60+Number(s.slice(3));}
function offset(name){const s=raw(name).trim();if(!/^[+-][0-9]{2}:(?:00|15|30|45)$/.test(s))invalid(name,'偏移需带 + 或 -，以 15 分钟递增。');const n=(Number(s.slice(1,3))*60+Number(s.slice(4)))*(s[0]==='-'?-1:1);if(n< -720||n>840)invalid(name,'偏移范围为 -12:00 至 +14:00。');return n;}
const mod=n=>(n%1440+1440)%1440,hhmm=n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');
function overlaps(){const a=time('aStart'),ae=time('aEnd'),ao=offset('aOffset'),b=time('bStart'),be=time('bEnd'),bo=offset('bOffset');if(a===ae)invalid('aEnd','A 开始与结束不可相同。');if(b===be)invalid('bEnd','B 开始与结束不可相同。');const da=mod(ae-a),db=mod(be-b),mask=Array.from({length:1440},(_,u)=>mod(u+ao-a)<da&&mod(u+bo-b)<db),runs=[];let start=-1;for(let i=0;i<=1440;i++){if(i<1440&&mask[i]){if(start<0)start=i;}else if(start>=0){runs.push([start,i]);start=-1;}}const local=(s,e,o)=>{const begin=mod(s+o),end=mod(e+o);return hhmm(begin)+'–'+hhmm(end)+(begin+(e-s)>=1440?'（跨午夜）':'');};return ['固定偏移交集报告','A 时长：'+da+' 分钟','B 时长：'+db+' 分钟','交集：'+mask.filter(Boolean).length+' 分钟','UTC 分段：'+runs.length,'',...runs.map(([s,e],i)=>(i+1)+'. UTC '+hhmm(s)+'–'+hhmm(e)+' · '+(e-s)+' 分钟\nA '+local(s,e,ao)+'；B '+local(s,e,bo)),runs.length?'':'没有交集。','','按循环日与固定偏移计算，不含具体日期或夏令时。'].join('\n');}
function quoteDepth(){const list=rows('quoted');let max=0,previous=0,jumps=0,quoted=0;const details=list.map((r,i)=>{if(length(r.value)>500)invalid('quoted','第 '+r.line+' 行超过 500 码点。');let body=r.value,depth=0;while(body.startsWith('>')){depth++;body=body.slice(1).trimStart();if(depth>20)invalid('quoted','第 '+r.line+' 行超过 20 层。');}if(!body)invalid('quoted','第 '+r.line+' 行缺少引用正文。');const jump=depth>previous+1;if(jump)jumps++;if(depth)quoted++;max=Math.max(max,depth);previous=depth;return (i+1)+'. 第 '+r.line+' 行 · 层级 '+depth+(jump?' · 跳级':'')+'\n'+body;});return ['引用层级报告','有效行：'+list.length,'引用行：'+quoted,'最大层级：'+max,'跳级：'+jumps,'',...details,'','结构检查不代表对话事实核验。'].join('\n');}
function utc(value,line){if(!/^20[0-9]{2}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}$/.test(value))invalid('turns','第 '+line+' 行需要 2000–2099 年的 YYYY-MM-DD HH:mm UTC 时间。');const [y,m,d,h,min]=value.match(/[0-9]+/g).map(Number),date=new Date(Date.UTC(y,m-1,d,h,min));if(date.getUTCFullYear()!==y||date.getUTCMonth()!==m-1||date.getUTCDate()!==d||date.getUTCHours()!==h||date.getUTCMinutes()!==min)invalid('turns','第 '+line+' 行包含不存在的日期或时刻。');return date.getTime();}
function turnaround(){const list=rows('turns'),minutes=[];const details=list.map((r,i)=>{const parts=r.value.split('|').map(s=>s.trim());if(parts.length!==3||!parts[0]||length(parts[0])>40)invalid('turns','第 '+r.line+' 行需要 标记 | UTC 开始 | UTC 结束；标记最多 40 码点。');const start=utc(parts[1],r.line),end=utc(parts[2],r.line);if(end<start)invalid('turns','第 '+r.line+' 行结束早于开始。');const n=(end-start)/60000;minutes.push(n);return (i+1)+'. 第 '+r.line+' 行 · '+parts[0]+' · '+n+' 分钟\n'+parts[1]+' → '+parts[2]+' UTC';});const sorted=minutes.slice().sort((a,b)=>a-b),n=sorted.length,total=minutes.reduce((a,b)=>a+b,0),median=n%2?sorted[(n-1)/2]:(sorted[n/2-1]+sorted[n/2])/2;return ['往返时长报告','记录：'+n,'总时长：'+total+' 分钟','最短：'+sorted[0]+' 分钟','最长：'+sorted[n-1]+' 分钟','平均：'+(total/n).toFixed(2)+' 分钟','中位数：'+median+' 分钟','P90：'+sorted[Math.ceil(.9*n)-1]+' 分钟','',...details,'','自然分钟差，不扣非工作时间，不是服务时效承诺。'].join('\n');}
const run=[subjects,enclosures,overlaps,quoteDepth,turnaround][Number(form.dataset.sorter)];
form.addEventListener('input',()=>{clear();status.textContent='输入已变化，请重新生成报告。';});
form.addEventListener('change',event=>{if(event.target.tagName==='SELECT'){clear();status.textContent='输入已变化，请重新生成报告。';}});
form.addEventListener('submit',event=>{event.preventDefault();clear();try{report.textContent=run();copyButton.disabled=false;status.textContent='完整回执已生成。';}catch(error){if(!error.field)throw error;const field=form.elements[error.field],message=form.querySelector('[data-field-error="'+error.field+'"]');message.textContent=error.message;field.setAttribute('aria-invalid','true');field.setAttribute('aria-errormessage',message.id);field.focus();status.textContent='未生成结果，请修正标记的输入。';}});
form.addEventListener('reset',()=>{clear();setTimeout(()=>{status.textContent='已恢复示例，生成后查看回执。';},0);});
copyButton.addEventListener('click',async()=>{if(copyButton.disabled)return;const version=revision,value=report.textContent;try{await copy(value);if(version===revision)copyState.textContent='完整回执已复制。';}catch{if(version===revision)copyState.textContent='复制不可用，请手动选择回执。';}});
})();
