(() => {
  "use strict";
  const main=document.querySelector("[data-dw86-tool]"),form=document.querySelector("[data-dw86-tool-form]");
  if(!main||!form)return;
  const kind=main.dataset.dw86Tool,input=form.querySelector("#dw86-input"),submit=form.querySelector("button[type=submit]"),errorNode=form.querySelector("[data-dw86-error]"),report=document.querySelector("[data-dw86-report]"),countNode=report.querySelector("[data-dw86-count]"),output=report.querySelector("[data-dw86-output]"),copy=report.querySelector("[data-dw86-result-copy]"),copyStatus=report.querySelector("[data-dw86-copy-status]");
  let currentReport="",revision=0;
  submit.disabled=false;
  const points=value=>Array.from(value).length;
  const hasControl=value=>/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/u.test(value);
  const hasUnpaired=value=>{for(let i=0;i<value.length;i+=1){const c=value.charCodeAt(i);if(c>=0xd800&&c<=0xdbff){const n=value.charCodeAt(i+1);if(!(n>=0xdc00&&n<=0xdfff))return true;i+=1;}else if(c>=0xdc00&&c<=0xdfff)return true;}return false;};
  const invalidate=()=>{revision+=1;currentReport="";input.removeAttribute("aria-invalid");input.removeAttribute("aria-errormessage");errorNode.textContent="";copyStatus.textContent="";copy.disabled=true;report.hidden=true;output.textContent="";countNode.textContent="0 ROWS";};
  const fail=message=>{invalidate();input.setAttribute("aria-invalid","true");input.setAttribute("aria-errormessage",errorNode.id);errorNode.textContent=message;input.focus();};
  const key=value=>value.normalize("NFKC").toLocaleLowerCase();
  const rows=parts=>{const raw=input.value;if(raw.length>40000||points(raw)>40000)throw new Error("总输入不能超过 40,000 个 Unicode 字符。");if(hasControl(raw))throw new Error("输入包含不允许的控制字符；换行、回车和制表符除外。");if(hasUnpaired(raw))throw new Error("输入包含不完整的 Unicode 代理对。");const lines=raw.split(/\r?\n/u).filter(line=>line.trim());if(!lines.length)throw new Error("请至少输入 1 条记录。");if(lines.length>300)throw new Error("非空记录不能超过 300 行。");return lines.map((source,index)=>{const fields=source.normalize("NFKC").replaceAll("−","-").split("|").map(field=>field.trim());if(fields.length!==parts)throw new Error("第 "+(index+1)+" 行须且只能包含 "+(parts-1)+" 个竖线分隔符。");if(fields.some(field=>!field))throw new Error("第 "+(index+1)+" 行存在空字段。");if(fields.some(field=>points(field)>100))throw new Error("第 "+(index+1)+" 行单个字段不能超过 100 个 Unicode 字符。");return{fields,line:index+1};});};
  const integer=(value,line,label,min,max)=>{if(!/^(?:0|[1-9][0-9]*)$/u.test(value))throw new Error("第 "+line+" 行"+label+"须为无前导零的十进制整数。");const number=Number(value);if(!Number.isSafeInteger(number)||number<min||number>max)throw new Error("第 "+line+" 行"+label+"须在 "+min+"–"+max+" 之间。");return number;};
  const gcd=(a,b)=>{let x=a,y=b;while(y){const t=x%y;x=y;y=t;}return x;};
  const ratio3=(value,total)=>{const v=BigInt(value),t=BigInt(total),scaled=(v*100000n+t/2n)/t;return(scaled/1000n).toString()+"."+(scaled%1000n).toString().padStart(3,"0")+"%";};
  const pairwise=()=>{const records=rows(3),pairs=new Set(),people=new Map();records.forEach(({fields,line})=>{const left=key(fields[0]),right=key(fields[1]),winner=key(fields[2]);if(left===right)throw new Error("第 "+line+" 行不能让选项与自己比较。");if(winner!==left&&winner!==right)throw new Error("第 "+line+" 行胜出选项必须与前两个选项之一完全一致。");const pair=[left,right].sort().join("\u0000");if(pairs.has(pair))throw new Error("第 "+line+" 行重复记录同一组选项。");pairs.add(pair);[[left,fields[0]],[right,fields[1]]].forEach(([k,label])=>{if(!people.has(k))people.set(k,{label,wins:0,losses:0,first:people.size});});people.get(winner).wins+=1;people.get(winner===left?right:left).losses+=1;});const ranked=[...people.values()].sort((a,b)=>(b.wins-b.losses)-(a.wins-a.losses)||b.wins-a.wins||a.first-b.first),out=["两两偏好完整报告","对局："+records.length,"选项："+people.size,""];ranked.forEach((x,i)=>out.push((i+1)+". "+x.label+"｜胜 "+x.wins+"｜负 "+x.losses+"｜Copeland "+(x.wins-x.losses)));out.push("","边界：净胜分只描述已输入的两两选择；缺失对局、不传递偏好和选择理由仍需人工复核。");return{count:records.length,text:out.join("\n")};};
  const weights=()=>{const records=rows(2).map(({fields,line},order)=>({label:fields[0],key:key(fields[0]),weight:integer(fields[1],line,"权重",1,1000000),line,order})),seen=new Set();records.forEach(x=>{if(seen.has(x.key))throw new Error("第 "+x.line+" 行标准名称重复。");seen.add(x.key);});const total=records.reduce((sum,x)=>sum+x.weight,0),divisor=records.reduce((value,x)=>gcd(value,x.weight),0),out=["权重公约数化简报告","标准："+records.length,"权重总和："+total,"最大公约数："+divisor,"","最简整数比："+records.map(x=>x.weight/divisor).join(" : "),""];records.forEach(x=>out.push(x.label+"｜权重 "+x.weight+"｜占比 "+ratio3(x.weight,total)));out.push("","边界：化简与占比不解释权重理由，也不证明标准之间相互独立或量表有效。");return{count:records.length,text:out.join("\n")};};
  const evidence=()=>{const records=rows(3).map(({fields,line})=>{const stance=fields[2].toUpperCase();if(!["SUPPORT","CHALLENGE"].includes(stance))throw new Error("第 "+line+" 行立场须为 SUPPORT 或 CHALLENGE。");return{claim:fields[0],claimKey:key(fields[0]),source:fields[1],sourceKey:key(fields[1]),stance,line};}),pairs=new Set(),groups=new Map();records.forEach(x=>{const pair=x.claimKey+"\u0000"+x.sourceKey;if(pairs.has(pair))throw new Error("第 "+x.line+" 行同一主张与来源重复。");pairs.add(pair);if(!groups.has(x.claimKey))groups.set(x.claimKey,{label:x.claim,rows:[]});groups.get(x.claimKey).rows.push(x);});const out=["证据正反面完整报告","记录："+records.length,"主张："+groups.size,""];let balanced=0;groups.forEach(g=>{const support=g.rows.filter(x=>x.stance==="SUPPORT").length,challenge=g.rows.length-support;if(support&&challenge)balanced+=1;out.push(g.label+"｜独立来源 "+g.rows.length+"｜支持 "+support+"｜挑战 "+challenge+"｜"+(support&&challenge?"双面记录":"单面记录"));});out.splice(3,0,"双面主张："+balanced);out.push("","边界：工具只检查来源标识和立场分布，不验证来源独立性、内容真实性或证据强度。");return{count:records.length,text:out.join("\n")};};
  const gates=()=>{const records=rows(3).map(({fields,line})=>{const state=fields[2].toUpperCase();if(!["PASS","FAIL"].includes(state))throw new Error("第 "+line+" 行状态须为 PASS 或 FAIL。");return{option:fields[0],optionKey:key(fields[0]),gate:fields[1],gateKey:key(fields[1]),state,line};}),pairs=new Set(),gates=new Map(),options=new Map();records.forEach(x=>{const pair=x.optionKey+"\u0000"+x.gateKey;if(pairs.has(pair))throw new Error("第 "+x.line+" 行选项与门槛重复。");pairs.add(pair);if(!gates.has(x.gateKey))gates.set(x.gateKey,x.gate);if(!options.has(x.optionKey))options.set(x.optionKey,{label:x.option,values:new Map()});options.get(x.optionKey).values.set(x.gateKey,x.state);});const out=["硬门槛覆盖完整报告","记录："+records.length,"选项："+options.size,"门槛："+gates.size,""];options.forEach(x=>{const missing=[...gates].filter(([k])=>!x.values.has(k)).map(([,label])=>label),failed=[...x.values].filter(([,state])=>state==="FAIL").map(([k])=>gates.get(k));out.push(x.label+"｜缺失 "+(missing.join(",")||"无")+"｜失败 "+(failed.join(",")||"无")+"｜"+(!missing.length&&!failed.length?"全部通过":"不可通过"));});out.push("","边界：必需门槛来自输入并集；工具不判断门槛是否合法、充分或已由权威材料证实。");return{count:records.length,text:out.join("\n")};};
  const regret=()=>{const records=rows(3).map(({fields,line},order)=>({option:fields[0],optionKey:key(fields[0]),scenario:fields[1],scenarioKey:key(fields[1]),cost:integer(fields[2],line,"成本",0,1000000),line,order})),pairs=new Set(),scenarios=new Map(),options=new Map();records.forEach(x=>{const pair=x.optionKey+"\u0000"+x.scenarioKey;if(pairs.has(pair))throw new Error("第 "+x.line+" 行选项与场景重复。");pairs.add(pair);if(!scenarios.has(x.scenarioKey))scenarios.set(x.scenarioKey,x.scenario);if(!options.has(x.optionKey))options.set(x.optionKey,{label:x.option,values:new Map(),first:x.order});options.get(x.optionKey).values.set(x.scenarioKey,x.cost);});options.forEach(x=>{const missing=[...scenarios.keys()].filter(k=>!x.values.has(k));if(missing.length)throw new Error(x.label+" 缺少场景："+missing.map(k=>scenarios.get(k)).join(",")+"。");});const minima=new Map([...scenarios.keys()].map(k=>[k,Math.min(...[...options.values()].map(x=>x.values.get(k)))]));const ranked=[...options.values()].map(x=>({...x,regrets:[...scenarios.keys()].map(k=>x.values.get(k)-minima.get(k))})).map(x=>({...x,max:Math.max(...x.regrets)})).sort((a,b)=>a.max-b.max||a.first-b.first),out=["最小最大后悔值完整报告","记录："+records.length,"选项："+options.size,"场景："+scenarios.size,""];ranked.forEach((x,i)=>out.push((i+1)+". "+x.label+"｜逐场景后悔值 "+x.regrets.join(",")+"｜最大后悔值 "+x.max));out.push("","边界：方法采用输入成本的逐场景最小值；不推断场景概率、成本真实性或风险偏好。");return{count:records.length,text:out.join("\n")};};
  const scans={pairwise,weights,evidence,gates,regret};
  const presets={
    pairwise:{standard:"甲 | 乙 | 甲\n甲 | 丙 | 丙\n乙 | 丙 | 乙",edge:"唯一甲 | 唯一乙 | 唯一甲",fullwidth:"甲 ｜ 乙 ｜ 甲"},
    weights:{standard:"可靠性 | 40\n速度 | 25\n成本 | 15",edge:"最小 | 1\n最大 | 1000000",fullwidth:"可靠性 ｜ ４０\n速度 ｜ ２０"},
    evidence:{standard:"主张甲 | 来源一 | SUPPORT\n主张甲 | 来源二 | CHALLENGE",edge:"单面 | 来源 | SUPPORT",fullwidth:"主张 ｜ 来源甲 ｜ ＳＵＰＰＯＲＴ\n主张 ｜ 来源乙 ｜ ＣＨＡＬＬＥＮＧＥ"},
    gates:{standard:"甲 | 合规 | PASS\n甲 | 预算 | FAIL\n乙 | 合规 | PASS\n乙 | 预算 | PASS",edge:"唯一 | 门槛 | PASS",fullwidth:"甲 ｜ 合规 ｜ ＰＡＳＳ\n乙 ｜ 合规 ｜ ＦＡＩＬ"},
    regret:{standard:"甲 | 平稳 | 20\n甲 | 压力 | 70\n乙 | 平稳 | 35\n乙 | 压力 | 45",edge:"唯一 | 场景 | 0",fullwidth:"甲 ｜ 平稳 ｜ ２０\n乙 ｜ 平稳 ｜ ３５"}
  };
  input.addEventListener("input",invalidate);form.addEventListener("reset",()=>setTimeout(invalidate));form.addEventListener("submit",event=>{event.preventDefault();try{const result=scans[kind]();invalidate();currentReport=result.text;output.textContent=result.text;countNode.textContent=result.count+" ROWS";report.hidden=false;copy.disabled=false;output.focus();}catch(error){fail(error.message);}});
  form.querySelectorAll("[data-dw86-preset]").forEach(button=>button.addEventListener("click",()=>{input.value=presets[kind][button.dataset.dw86Preset];invalidate();input.focus();}));
  copy.addEventListener("click",async()=>{const capturedRevision=revision,capturedReport=currentReport;try{await navigator.clipboard.writeText(capturedReport);if(capturedRevision===revision&&capturedReport===currentReport&&currentReport)copyStatus.textContent="完整报告已复制。";}catch(_error){if(capturedRevision===revision)copyStatus.textContent="复制未完成，请手动选择报告。";}});
})();
