(function () {
  "use strict";
  const gates = ["FACTS", "QUOTE", "CONSENT", "CONTEXT"];
  const cp = (value) => [...value].length;
  const normalize = (value) => value.normalize("NFKC").trim();
  const key = (value) => normalize(value).toLocaleLowerCase();
  const control = /[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f-\u009f]/u;
  const hasUnpaired = (value) => { for (let index = 0; index < value.length; index += 1) { const unit = value.charCodeAt(index); if (unit >= 0xd800 && unit <= 0xdbff) { const next = value.charCodeAt(index + 1); if (!(next >= 0xdc00 && next <= 0xdfff)) return true; index += 1; } else if (unit >= 0xdc00 && unit <= 0xdfff) return true; } return false; };
  function lines(raw) { if (!raw.trim()) throw new Error("请输入至少一行记录。"); if (cp(raw) > 40000) throw new Error("输入不能超过 40,000 个 Unicode 字符。"); if (hasUnpaired(raw)) throw new Error("输入含有不完整的 Unicode 代理项。"); if (control.test(raw)) throw new Error("输入含有不允许的控制字符。"); const result = raw.split(/\r?\n/u).map((value, index) => ({ value: normalize(value), line: index + 1 })).filter((item) => item.value); if (result.length < 1 || result.length > 300) throw new Error("记录须为 1–300 个非空行。"); return result; }
  function fields(item, count, separator = "|") { const values = item.value.split(separator).map(normalize); if (values.length !== count || values.some((value) => !value)) throw new Error(`第 ${item.line} 行必须恰有 ${count} 个非空字段。`); if (values.some((value) => cp(value) > 240)) throw new Error(`第 ${item.line} 行字段不能超过 240 个 Unicode 字符。`); return values; }
  function relation(seen, left, right, line) { const token = `${key(left)}\u0000${key(right)}`; if (seen.has(token)) throw new Error(`第 ${line} 行与前面的关系重复。`); seen.add(token); }
  function date(value, line) { if (!/^\d{4}-\d{2}-\d{2}$/u.test(value)) throw new Error(`第 ${line} 行日期必须为 YYYY-MM-DD。`); const [year, month, day] = value.split("-").map(Number), parsed = new Date(Date.UTC(year, month - 1, day)); if (parsed.getUTCFullYear() !== year || parsed.getUTCMonth() !== month - 1 || parsed.getUTCDate() !== day) throw new Error(`第 ${line} 行包含不存在的日期。`); return parsed; }
  const engines = {
    identity(input) { const seen = new Set(), replacements = new Set(), rows = []; for (const item of input) { const [source, replacement] = fields(item, 2, "||"); if (cp(source) < 2 || cp(replacement) < 2) throw new Error(`第 ${item.line} 行两侧各至少 2 个字符。`); const sourceKey = key(source), replacementKey = key(replacement); if (sourceKey === replacementKey) throw new Error(`第 ${item.line} 行替换前后不能相同。`); if (seen.has(sourceKey)) throw new Error(`第 ${item.line} 行原标识重复。`); seen.add(sourceKey); replacements.add(replacementKey); rows.push(`${source} → ${replacement}`); } return ["IDENTITY MAP / COMPLETE", `映射：${rows.length}`, `公开代称：${replacements.size}`, `重复原标识：0`, "", ...rows].join("\n"); },
    quotes(input) { const seen = new Set(), portraits = new Set(); let verified = 0, open = 0; const rows = []; for (const item of input) { const [quote, source, rawState] = fields(item, 3), state = rawState.toLocaleUpperCase(); if (!new Set(["VERIFIED", "OPEN"]).has(state)) throw new Error(`第 ${item.line} 行状态只能是 VERIFIED 或 OPEN。`); relation(seen, quote, source, item.line); portraits.add(key(quote)); if (state === "VERIFIED") verified += 1; else open += 1; rows.push(`${quote} ← ${source} | ${state}`); } return ["QUOTE SOURCE / COMPLETE", `引语：${portraits.size}`, `独立关系：${seen.size}`, `已核对：${verified}`, `待核对：${open}`, "", ...rows].join("\n"); },
    consent(input) { const seen = new Set(), subjects = new Map(); for (const item of input) { const [subject, use, rawState] = fields(item, 3), state = rawState.toLocaleUpperCase(); if (!new Set(["ALLOWED", "RESTRICTED"]).has(state)) throw new Error(`第 ${item.line} 行状态只能是 ALLOWED 或 RESTRICTED。`); relation(seen, subject, use, item.line); const token = key(subject); if (!subjects.has(token)) subjects.set(token, { label: subject, allowed: 0, restricted: 0 }); subjects.get(token)[state === "ALLOWED" ? "allowed" : "restricted"] += 1; } const restricted = [...subjects.values()].reduce((sum, subject) => sum + subject.restricted, 0); return ["CONSENT SCOPE / COMPLETE", `人物：${subjects.size}`, `使用关系：${seen.size}`, `受限使用：${restricted}`, "", ...[...subjects.values()].map((subject) => `${subject.label} | ALLOWED ${subject.allowed} | RESTRICTED ${subject.restricted}`)].join("\n"); },
    timeline(input) { const events = new Set(), orders = new Set(), rows = []; for (const item of input) { const [event, rawDate, rawOrder] = fields(item, 3); if (!/^\d+$/u.test(rawOrder)) throw new Error(`第 ${item.line} 行顺序必须是整数。`); const order = Number(rawOrder); if (order < 1 || order > 9999) throw new Error(`第 ${item.line} 行顺序须为 1–9999。`); if (events.has(key(event))) throw new Error(`第 ${item.line} 行事件名称重复。`); if (orders.has(order)) throw new Error(`第 ${item.line} 行顺序重复。`); events.add(key(event)); orders.add(order); rows.push({ event, date: date(rawDate, item.line), rawDate, order }); } rows.sort((a, b) => a.order - b.order); let reversals = 0; for (let index = 1; index < rows.length; index += 1) if (rows[index].date < rows[index - 1].date) reversals += 1; return ["TIMELINE PROOF / COMPLETE", `事件：${rows.length}`, `日期逆序：${reversals}`, `状态：${reversals ? "REVIEW" : "READY"}`, "", ...rows.map((row) => `${row.order}. ${row.event} | ${row.rawDate}`)].join("\n"); },
    release(input) { const seen = new Set(), portraits = new Map(); for (const item of input) { const [portrait, rawGate, rawState] = fields(item, 3), gate = rawGate.toLocaleUpperCase(), state = rawState.toLocaleUpperCase(); if (!gates.includes(gate)) throw new Error(`第 ${item.line} 行门项必须是 ${gates.join("、")}。`); if (!new Set(["PASS", "OPEN"]).has(state)) throw new Error(`第 ${item.line} 行状态只能是 PASS 或 OPEN。`); relation(seen, portrait, gate, item.line); const token = key(portrait); if (!portraits.has(token)) portraits.set(token, { label: portrait, gates: new Map() }); portraits.get(token).gates.set(gate, state); } let ready = 0, blocked = 0; const rows = []; for (const portrait of portraits.values()) { const missing = gates.filter((gate) => !portrait.gates.has(gate)), open = gates.filter((gate) => portrait.gates.get(gate) === "OPEN"), state = !missing.length && !open.length ? "READY" : "BLOCKED"; if (state === "READY") ready += 1; else blocked += 1; rows.push(`${portrait.label} | ${state} | 缺项 ${missing.join("、") || "无"} | 待处理 ${open.join("、") || "无"}`); } return ["RELEASE GATE / COMPLETE", `人物：${portraits.size}`, `READY：${ready}`, `BLOCKED：${blocked}`, "", ...rows].join("\n"); }
  };
  async function copy(value, output, revision, current) { try { if (navigator.clipboard && window.isSecureContext) await navigator.clipboard.writeText(value); else { const field = document.createElement("textarea"); field.value = value; field.setAttribute("readonly", ""); field.style.position = "fixed"; field.style.opacity = "0"; document.body.append(field); field.select(); const okay = document.execCommand("copy"); field.remove(); if (!okay) throw new Error("copy unavailable"); } if (revision === current()) output.textContent = "报告已复制。"; } catch (_error) { if (revision === current()) output.textContent = "复制失败，请手动选择报告。"; } }
  document.querySelectorAll("[data-pj90-instrument]").forEach((shell) => { const engine = engines[shell.dataset.pj90Instrument], form = shell.querySelector("form"), input = shell.querySelector("textarea"), error = shell.querySelector("[data-pj90-tool-error]"), status = shell.querySelector("[data-pj90-tool-status]"), state = shell.querySelector("[data-pj90-tool-state]"), report = shell.querySelector("[data-pj90-tool-report]"), copyButton = shell.querySelector("[data-pj90-tool-copy]"), copyStatus = shell.querySelector("[data-pj90-tool-copy-status]"); let last = "", revision = 0; const stale = () => { revision += 1; last = ""; error.textContent = ""; status.textContent = "输入已更改，请重新检查。"; state.textContent = "STALE"; report.textContent = "旧报告已失效。"; copyButton.disabled = true; copyStatus.textContent = ""; }; const reset = () => { revision += 1; last = ""; error.textContent = ""; status.textContent = "等待输入。"; state.textContent = "UNSET"; report.textContent = "检查结果将在这里显示。"; copyButton.disabled = true; copyStatus.textContent = ""; }; input.addEventListener("input", stale); form.addEventListener("reset", () => setTimeout(reset, 0)); form.addEventListener("submit", (event) => { event.preventDefault(); revision += 1; copyStatus.textContent = ""; try { last = engine(lines(input.value)); error.textContent = ""; status.textContent = "检查完成。"; state.textContent = "COMPLETE"; report.textContent = last; copyButton.disabled = false; } catch (problem) { last = ""; error.textContent = problem instanceof Error ? problem.message : "输入无效。"; status.textContent = "检查未完成。"; state.textContent = "INVALID"; report.textContent = "请修正输入后重新检查；旧报告已清除。"; copyButton.disabled = true; input.focus(); } }); copyButton.addEventListener("click", () => { if (last) copy(last, copyStatus, revision, () => revision); }); });
})();
