(() => {
 'use strict';
 const one=s=>document.querySelector(s),all=s=>Array.from(document.querySelectorAll(s)),html=document.documentElement,rail=one('.af69-rail'),menu=one('#af69-menu'),menuButton=one('#af69-menu-button'),themeButton=one('[data-signal-toggle]'),themeKey='azure-feed-069-signal';
 function theme(value){html.dataset.signal=value==='deep'?'deep':'light';if(themeButton){themeButton.textContent=html.dataset.signal==='deep'?'天青':'深蓝';themeButton.setAttribute('aria-label',html.dataset.signal==='deep'?'切换到天青主题':'切换到深蓝主题');}one('meta[name="theme-color"]').content=html.dataset.signal==='deep'?'#091b28':'#e9f2f5';}
 try{theme(localStorage.getItem(themeKey));}catch{theme('light');}
 if(themeButton){themeButton.hidden=false;themeButton.addEventListener('click',()=>{theme(html.dataset.signal==='deep'?'light':'deep');try{localStorage.setItem(themeKey,html.dataset.signal);}catch{}});}
 function closeMenu(focus=false){if(!menuButton)return;menu.classList.remove('af69-open');menuButton.setAttribute('aria-expanded','false');if(focus)menuButton.focus();}
 if(menuButton){rail.classList.add('af69-js');menuButton.hidden=false;menuButton.addEventListener('click',()=>{if(menuButton.getAttribute('aria-expanded')==='true')closeMenu();else{menu.classList.add('af69-open');menuButton.setAttribute('aria-expanded','true');menu.querySelector('a').focus();}});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>closeMenu()));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menuButton.getAttribute('aria-expanded')==='true')closeMenu(true);});document.addEventListener('click',e=>{if(!rail.contains(e.target))closeMenu();});matchMedia('(min-width:901px)').addEventListener('change',e=>{if(e.matches)closeMenu();});}
 const codeButton=one('[data-copy-code]');if(codeButton){codeButton.disabled=false;codeButton.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(one('#af69-code').textContent.trim());one('[data-code-state]').textContent='代码已复制。';}catch{one('[data-code-state]').textContent='剪贴板不可用，请手动选择代码复制。';}});}
 const key=s=>s.normalize('NFKC').trim().toLowerCase();
 const filter=one('[data-stream-filter]');if(filter){filter.hidden=false;const update=()=>{const q=key(filter.elements.keyword.value),c=filter.elements.channel.value;let count=0;all('[data-dispatch-channel]').forEach(item=>{item.hidden=!((c==='all'||c===item.dataset.dispatchChannel)&&key(item.querySelector('a').textContent).includes(q));if(!item.hidden)count++;});one('[data-filter-state]').textContent='显示 '+count+' 篇。';};filter.addEventListener('input',update);filter.addEventListener('change',update);filter.addEventListener('reset',()=>setTimeout(update,0));update();}
 const search=one('[data-local-search]');if(search){search.querySelector('button').disabled=false;search.addEventListener('submit',e=>{e.preventDefault();const q=key(search.elements.query.value);let count=0;all('[data-search-item]').forEach(a=>{a.hidden=!key(a.textContent).includes(q);if(!a.hidden)count++;});one('[data-search-state]').textContent=count?'找到 '+count+' 个页面。':'未找到匹配题名，可尝试更短的关键词。';});}
 const progress=one('[data-reading-progress]');if(progress){let pending=false;const update=()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max>0?Math.min(100,Math.max(0,scrollY/max*100)):100)+'%';pending=false;};addEventListener('scroll',()=>{if(!pending){pending=true;requestAnimationFrame(update);}},{passive:true});addEventListener('resize',update);addEventListener('load',update);update();}
 const form=one('[data-processor]');if(!form)return;
 const output=one('[data-result-text]'),status=one('[data-result-status]'),copy=one('[data-copy-result]'),copyState=one('[data-result-copy-state]'),error=one('#af69-error');let revision=0;
 const raw=name=>form.elements.namedItem(name).value;
 function fail(field,message){const e=new Error(message);e.field=field;throw e;}
 function text(name,max,empty=false){const s=raw(name);if(!s.isWellFormed())fail(name,'输入含不完整 Unicode，请重新输入。');if(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f-\u009f]/u.test(s))fail(name,'输入含不可用控制字符。');if(Array.from(s).length>max)fail(name,'输入超过 '+max+' Unicode 码点。');if(!empty&&!s.length)fail(name,'请填写此字段。');return s;}
 const normalizeLines=s=>s.replace(/\r\n?/g,'\n');
 function lines(name){const s=normalizeLines(text(name,8000,true)),rows=s===''?[]:s.split('\n');if(rows.length>100)fail(name,'每侧最多 100 行，末尾换行也会形成一行。');rows.forEach((r,i)=>{if(Array.from(r).length>300)fail(name,'第 '+(i+1)+' 行超过 300 码点。');});return rows;}
 const algorithms={
  'card-segments':()=>{const s=normalizeLines(text('cards',10000));if(!s.trim())fail('cards','至少输入一张非空卡片。');const blocks=s.trim().split(/\n\s*\n+/).map(t=>t.normalize('NFKC').replace(/\s+/g,' ').trim()).filter(Boolean);if(blocks.length>60)fail('cards','最多接受 60 张卡片。');const seen=new Map(),cards=blocks.map((s,i)=>{const length=Array.from(s).length;if(length>1000)fail('cards','第 '+(i+1)+' 张卡片超过 1,000 码点。');const k=s.toLowerCase(),duplicate=seen.get(k)||0;if(!seen.has(k))seen.set(k,i+1);return {s,length,duplicate};});return ['动态卡分段报告','卡片：'+cards.length,'总码点：'+cards.reduce((a,c)=>a+c.length,0),'重复卡：'+cards.filter(c=>c.duplicate).length,'超过 280 码点：'+cards.filter(c=>c.length>280).length,'',...cards.flatMap((c,i)=>[(i+1)+'. '+c.length+' 码点'+(c.duplicate?'；重复第 '+c.duplicate+' 张':'')+(c.length>280?'；超过建议线':''),c.s,'']),'长度和完全重复仅描述文本结构，不判断内容价值。'].join('\n');},
  'line-revision':()=>{const before=lines('before'),after=lines('after'),n=before.length,m=after.length,dp=Array.from({length:n+1},()=>new Uint16Array(m+1));for(let i=n-1;i>=0;i--)for(let j=m-1;j>=0;j--)dp[i][j]=before[i]===after[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);const rows=[];let i=0,j=0,kept=0,removed=0,added=0;while(i<n||j<m){if(i<n&&j<m&&before[i]===after[j]){rows.push('= '+(i+1)+':'+(j+1)+' | '+before[i]);kept++;i++;j++;}else if(i<n&&(j===m||dp[i+1][j]>=dp[i][j+1])){rows.push('- '+(i+1)+':– | '+before[i]);removed++;i++;}else{rows.push('+ –:'+(j+1)+' | '+after[j]);added++;j++;}}return ['逐行修订报告','旧文本行数：'+n,'新文本行数：'+m,'保留行：'+kept,'删除行：'+removed,'新增行：'+added,'','= 保留 / - 删除 / + 新增；编号为旧行:新行',...(rows.length?rows:['两侧均为空，没有修订。']),'','只比较整行，保留大小写与空格；不判断修改的语义。'].join('\n');},
  'byte-budget':()=>{const s=text('text',10000,true),budgetText=text('budget',20).trim();if(!/^\d+$/.test(budgetText))fail('budget','容量只接受十进制整数。');const budget=Number(budgetText);if(!Number.isSafeInteger(budget)||budget<1||budget>100000)fail('budget','容量须在 1–100,000 字节之间。');const encode=t=>new TextEncoder().encode(t).length,bytes=encode(s),points=Array.from(s).length,rows=s===''?[]:s.split(/\r\n|\r|\n/),lineBytes=rows.map(encode),separators=bytes-lineBytes.reduce((a,b)=>a+b,0);return ['UTF-8 字节预算报告','Unicode 码点：'+points,'UTF-16 代码单元：'+s.length,'UTF-8 字节：'+bytes,'给定容量：'+budget+' 字节',bytes<=budget?'剩余容量：'+(budget-bytes)+' 字节':'超出容量：'+(bytes-budget)+' 字节','占用：'+(bytes/budget*100).toFixed(2)+'%','换行字节：'+separators,'','各行内容字节（不含分隔符）',...(rows.length?lineBytes.map((b,i)=>(i+1)+'. '+b+' 字节'):['空文本，没有内容行。']),'','当前控件文本按 UTF-8 编码；不是可见字符数、字宽或网页大小。'].join('\n');},
  'literal-locator':()=>{const source=text('text',4000,true),needle=text('needle',100),hay=Array.from(source),word=Array.from(needle),overlap=raw('overlap');if(!['yes','no'].includes(overlap))fail('overlap','请选择有效重叠规则。');const lineAt=[],columnAt=[];let line=1,column=1;hay.forEach(c=>{lineAt.push(line);columnAt.push(column);if(c==='\n'){line++;column=1;}else column++;});const hits=[];for(let i=0;i<=hay.length-word.length;){let match=true;for(let j=0;j<word.length;j++)if(hay[i+j]!==word[j]){match=false;break;}if(match){hits.push({start:i+1,end:i+word.length,line:lineAt[i],column:columnAt[i]});i+=overlap==='yes'?1:word.length;}else i++;}return ['原文定位报告','原文码点：'+hay.length,'查找码点：'+word.length,'查找文字：'+JSON.stringify(needle),'重叠：'+(overlap==='yes'?'允许':'不允许'),'匹配数：'+hits.length,'',...(hits.length?hits.map((h,i)=>(i+1)+'. 位置 '+h.start+'–'+h.end+'；行 '+h.line+'，列 '+h.column):['没有字面匹配。']),'','所有位置从 1 开始，按 Unicode 码点计数；列号不是可见字宽。'].join('\n');},
  'field-inventory':()=>{const s=text('fields',10000);if(!s.trim())fail('fields','至少填写一条键值记录。');const rows=normalizeLines(s).split('\n').map((text,i)=>({text:text.normalize('NFKC').trim(),line:i+1})).filter(r=>r.text);if(rows.length>120)fail('fields','最多接受 120 非空行。');const groups=new Map();let empty=0;rows.forEach(r=>{const at=r.text.indexOf(':');if(at<0)fail('fields','第 '+r.line+' 行缺少冒号。');const label=r.text.slice(0,at).trim(),value=r.text.slice(at+1).trim();if(!label||Array.from(label).length>40)fail('fields','第 '+r.line+' 行键须为 1–40 码点。');if(Array.from(value).length>200)fail('fields','第 '+r.line+' 行值超过 200 码点。');if(!value)empty++;const k=label.toLowerCase();if(!groups.has(k))groups.set(k,{label,rows:[]});groups.get(k).rows.push({line:r.line,value});if(groups.size>60)fail('fields','最多接受 60 个不同键。');});return ['键值字段索引报告','有效记录：'+rows.length,'不同键：'+groups.size,'重复记录：'+(rows.length-groups.size),'重复字段：'+[...groups.values()].filter(g=>g.rows.length>1).length,'空值记录：'+empty,'',...[...groups.values()].flatMap((g,i)=>[(i+1)+'. '+g.label+'（'+g.rows.length+' 条）',...g.rows.map(r=>'第 '+r.line+' 行：'+(r.value||'（空值）')),'']),'仅检查结构，不判断字段值的真实性或完整性。'].join('\n');}
 };
 function clear(){revision++;output.textContent='';copy.disabled=true;copyState.textContent='';error.textContent='';form.querySelectorAll('[aria-invalid]').forEach(e=>{e.removeAttribute('aria-invalid');e.removeAttribute('aria-errormessage');});status.textContent='输入已变更，请重新生成';}
 form.querySelector('[type=submit]').disabled=false;
 form.addEventListener('input',clear);form.addEventListener('change',e=>{if(e.target.tagName==='SELECT')clear();});
 form.addEventListener('reset',()=>{clear();setTimeout(()=>{status.textContent='示例已恢复，等待生成';},0);});
 form.addEventListener('submit',e=>{e.preventDefault();clear();try{output.textContent=algorithms[form.dataset.processor]();copy.disabled=false;status.textContent='报告已生成';}catch(problem){error.textContent=problem.message;status.textContent='请检查输入';const control=form.elements.namedItem(problem.field);if(control){control.setAttribute('aria-invalid','true');control.setAttribute('aria-errormessage','af69-error');control.focus();}}});
 copy.addEventListener('click',async()=>{if(copy.disabled)return;const current=revision,value=output.textContent;try{await navigator.clipboard.writeText(value);if(current===revision)copyState.textContent='完整报告已复制。';}catch{if(current===revision)copyState.textContent='剪贴板不可用，请在结果区域手动选择复制。';}});
})();
