(() => {
  'use strict';
  const root=document.documentElement; root.classList.remove('tw55-nojs');
  const themeButton=document.getElementById('tw55-theme-button'), key='ticker-wire-055-theme';
  function theme(value){root.dataset.theme=value;themeButton.textContent=value==='dark'?'浅色':'深色';themeButton.setAttribute('aria-label',value==='dark'?'切换到浅色模式':'切换到深色模式');}
  let saved;try{saved=localStorage.getItem(key);}catch{/* Optional storage. */}theme(['dark','light'].includes(saved)?saved:'dark');
  themeButton.addEventListener('click',()=>{const next=root.dataset.theme==='dark'?'light':'dark';theme(next);try{localStorage.setItem(key,next);}catch{/* Current-page theme still works. */}});
  const menu=document.getElementById('tw55-console-btn'),nav=document.getElementById('tw55-console-nav');
  function close(restore=false){nav.classList.remove('tw55-lit');menu.setAttribute('aria-expanded','false');if(restore)menu.focus();}
  menu.addEventListener('click',()=>{const open=nav.classList.toggle('tw55-lit');menu.setAttribute('aria-expanded',String(open));if(open)nav.querySelector('a')?.focus();});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('tw55-lit'))close(true);});
  nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>close()));matchMedia('(min-width:621px)').addEventListener('change',e=>{if(e.matches)close();});
  const motion=matchMedia('(prefers-reduced-motion:reduce)'),motionButton=document.querySelector('[data-motion-toggle]');let paused=motion.matches;
  function updateMotion(){root.classList.toggle('tw55-motion-paused',paused);motionButton.disabled=motion.matches;motionButton.textContent=motion.matches?'静态模式':paused?'恢复动态':'暂停动态';motionButton.setAttribute('aria-pressed',String(paused));}
  motionButton.addEventListener('click',()=>{paused=!paused;updateMotion();});motion.addEventListener('change',()=>{if(motion.matches)paused=true;updateMotion();});updateMotion();
  const copy=document.querySelector('[data-copy-code]');copy?.addEventListener('click',async()=>{const status=document.querySelector('[data-code-state]');copy.disabled=true;status.textContent='';try{if(!navigator.clipboard?.writeText)throw new Error('Unavailable');await navigator.clipboard.writeText(document.getElementById('tw55-code').textContent.trim());status.textContent='邀请码已复制。';}catch{status.textContent='复制未获许可，请选择邀请码手动复制。';}finally{copy.disabled=false;}});
  document.querySelectorAll('[data-js-controls]').forEach(e=>{e.hidden=false;});
  const labels={verified:'已核验',review:'待复核',pending:'待确认'},signals=[...document.querySelectorAll('[data-signal-status]')];
  signals.forEach(item=>{if(!Object.hasOwn(labels,item.dataset.signalStatus))item.dataset.signalStatus='pending';item.querySelector('mark').textContent=labels[item.dataset.signalStatus];});
  const filters=[...document.querySelectorAll('[data-signal-filter]')];filters.forEach(button=>button.addEventListener('click',()=>{let count=0;signals.forEach(item=>{item.hidden=button.dataset.signalFilter!=='all'&&item.dataset.signalStatus!==button.dataset.signalFilter;if(!item.hidden)count++;});filters.forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelector('[data-signal-count]').textContent=count+' 条线索';}));
  const channelButtons=[...document.querySelectorAll('[data-channel-filter]')];channelButtons.forEach(button=>button.addEventListener('click',()=>{let count=0;document.querySelectorAll('[data-dispatch]').forEach(item=>{item.hidden=button.dataset.channelFilter!=='all'&&item.dataset.channel!==button.dataset.channelFilter;if(!item.hidden)count++;});channelButtons.forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelector('[data-filter-state]').textContent='当前频道有 '+count+' 个记录入口。';}));
  const search=document.querySelector('[data-local-search]');if(search){search.hidden=false;search.addEventListener('submit',e=>{e.preventDefault();const query=search.elements.query.value.normalize('NFKC').trim().toLowerCase();let count=0;document.querySelectorAll('[data-search-item]').forEach(item=>{item.hidden=!item.textContent.normalize('NFKC').toLowerCase().includes(query);if(!item.hidden)count++;});search.querySelector('[data-search-state]').textContent=count?'找到 '+count+' 个入口。':'没有匹配项；清空关键词可以显示全部入口。';});search.addEventListener('input',()=>{document.querySelectorAll('[data-search-item]').forEach(e=>{e.hidden=false;});search.querySelector('[data-search-state]').textContent='关键词已变化，请重新查找。';});}
  const progress=document.querySelector('[data-reading-progress]');if(progress){function update(){const range=document.documentElement.scrollHeight-innerHeight;progress.style.width=(range>0?Math.min(100,Math.max(0,scrollY/range*100)):100)+'%';}addEventListener('scroll',update,{passive:true});addEventListener('resize',update);update();}
})();
